

CREATE TABLE "ZHANG_DM1"."CONFIG_INFO"
(
    "ID" INT IDENTITY(1, 1) NOT NULL,
    "DATA_ID" NVARCHAR2(255 CHAR) NOT NULL,
    "GROUP_ID" NVARCHAR2(255 CHAR),
    "CONTENT" TEXT NOT NULL,
    "MD5" NVARCHAR2(32 CHAR),
    "GMT_CREATE" DATE DEFAULT SYSDATE() NOT NULL,
    "GMT_MODIFIED" DATE DEFAULT SYSDATE() NOT NULL,
    "SRC_USER" TEXT,
    "SRC_IP" NVARCHAR2(50 CHAR),
    "APP_NAME" NVARCHAR2(128 CHAR),
    "TENANT_ID" NVARCHAR2(128 CHAR) DEFAULT '',
    "C_DESC" NVARCHAR2(256 CHAR),
    "C_USE" NVARCHAR2(64 CHAR),
    "EFFECT" NVARCHAR2(64 CHAR),
    "TYPE" NVARCHAR2(64 CHAR),
    "C_SCHEMA" TEXT,
    "ENCRYPTED_DATA_KEY"  varchar(1024) DEFAULT '' NOT NULL,
    NOT CLUSTER PRIMARY KEY("ID")) STORAGE(ON "MAIN", CLUSTERBTR) ;

CREATE UNIQUE  INDEX "uk_configinfo_datagrouptenant" ON "ZHANG_DM1"."CONFIG_INFO"("DATA_ID" ASC,"GROUP_ID" ASC,"TENANT_ID" ASC) STORAGE(CLUSTERBTR) ;

CREATE TABLE "ZHANG_DM1"."CONFIG_INFO_AGGR"
(
    "ID" INT IDENTITY(1, 1) NOT NULL,
    "DATA_ID" NVARCHAR2(255 CHAR) NOT NULL,
    "GROUP_ID" NVARCHAR2(255 CHAR) NOT NULL,
    "DATUM_ID" NVARCHAR2(255 CHAR) NOT NULL,
    "CONTENT" TEXT NOT NULL,
    "GMT_MODIFIED" DATE NOT NULL,
    "APP_NAME" NVARCHAR2(128 CHAR),
    "TENANT_ID" NVARCHAR2(128 CHAR),
    NOT CLUSTER PRIMARY KEY("ID")) STORAGE(ON "MAIN", CLUSTERBTR) ;

CREATE TABLE "ZHANG_DM1"."CONFIG_INFO_BETA"
(
    "ID" INT IDENTITY(1, 1) NOT NULL,
    "DATA_ID" NVARCHAR2(255 CHAR) NOT NULL,
    "GROUP_ID" NVARCHAR2(128 CHAR) NOT NULL,
    "APP_NAME" NVARCHAR2(128 CHAR),
    "CONTENT" TEXT NOT NULL,
    "BETA_IPS" TEXT,
    "MD5" NVARCHAR2(32 CHAR),
    "GMT_CREATE" DATE NOT NULL,
    "GMT_MODIFIED" DATE NOT NULL,
    "SRC_USER" TEXT,
    "SRC_IP" NVARCHAR2(50 CHAR),
    "TENANT_ID" NVARCHAR2(128 CHAR),
    "ENCRYPTED_DATA_KEY"  varchar(1024) DEFAULT '' NOT NULL,
    NOT CLUSTER PRIMARY KEY("ID")) STORAGE(ON "MAIN", CLUSTERBTR) ;

CREATE TABLE "ZHANG_DM1"."CONFIG_INFO_TAG"
(
    "ID" INT IDENTITY(1, 1) NOT NULL,
    "DATA_ID" NVARCHAR2(255 CHAR) NOT NULL,
    "GROUP_ID" NVARCHAR2(128 CHAR) NOT NULL,
    "TENANT_ID" NVARCHAR2(128 CHAR),
    "TAG_ID" NVARCHAR2(128 CHAR) NOT NULL,
    "APP_NAME" NVARCHAR2(128 CHAR),
    "CONTENT" TEXT NOT NULL,
    "MD5" NVARCHAR2(32 CHAR),
    "GMT_CREATE" DATE NOT NULL,
    "GMT_MODIFIED" DATE NOT NULL,
    "SRC_USER" TEXT,
    "SRC_IP" NVARCHAR2(50 CHAR),
    NOT CLUSTER PRIMARY KEY("ID")) STORAGE(ON "MAIN", CLUSTERBTR) ;

CREATE TABLE "ZHANG_DM1"."CONFIG_TAGS_RELATION"
(
    "ID" NUMBER(20,0) NOT NULL,
    "TAG_NAME" NVARCHAR2(128 CHAR) NOT NULL,
    "TAG_TYPE" NVARCHAR2(64 CHAR),
    "DATA_ID" NVARCHAR2(255 CHAR) NOT NULL,
    "GROUP_ID" NVARCHAR2(128 CHAR) NOT NULL,
    "TENANT_ID" NVARCHAR2(128 CHAR),
    "NID" INT IDENTITY(1, 1) NOT NULL,
    NOT CLUSTER PRIMARY KEY("NID")) STORAGE(ON "MAIN", CLUSTERBTR) ;

CREATE TABLE "ZHANG_DM1"."GROUP_CAPACITY"
(
    "ID" INT IDENTITY(1, 1) NOT NULL,
    "GROUP_ID" NVARCHAR2(128 CHAR) NOT NULL,
    "QUOTA" NUMBER(11,0) NOT NULL,
    "USAGE" NUMBER(11,0) NOT NULL,
    "MAX_SIZE" NUMBER(11,0) NOT NULL,
    "MAX_AGGR_COUNT" NUMBER(11,0) NOT NULL,
    "MAX_AGGR_SIZE" NUMBER(11,0) NOT NULL,
    "MAX_HISTORY_COUNT" NUMBER(11,0) NOT NULL,
    "GMT_CREATE" DATE NOT NULL,
    "GMT_MODIFIED" DATE NOT NULL,
    NOT CLUSTER PRIMARY KEY("ID")) STORAGE(ON "MAIN", CLUSTERBTR) ;

COMMENT ON TABLE "ZHANG_DM1"."GROUP_CAPACITY" IS '集群、各Group容量信息表';
COMMENT ON COLUMN "ZHANG_DM1"."GROUP_CAPACITY"."ID" IS '主键ID';
COMMENT ON COLUMN "ZHANG_DM1"."GROUP_CAPACITY"."GROUP_ID" IS 'Group ID，空字符表示整个集群';
COMMENT ON COLUMN "ZHANG_DM1"."GROUP_CAPACITY"."QUOTA" IS '配额，0表示使用默认值';
COMMENT ON COLUMN "ZHANG_DM1"."GROUP_CAPACITY"."USAGE" IS '使用量';
COMMENT ON COLUMN "ZHANG_DM1"."GROUP_CAPACITY"."MAX_SIZE" IS '单个配置大小上限，单位为字节，0表示使用默认值';
COMMENT ON COLUMN "ZHANG_DM1"."GROUP_CAPACITY"."MAX_AGGR_COUNT" IS '聚合子配置最大个数，，0表示使用默认值';
COMMENT ON COLUMN "ZHANG_DM1"."GROUP_CAPACITY"."MAX_AGGR_SIZE" IS '单个聚合数据的子配置大小上限，单位为字节，0表示使用默认值';
COMMENT ON COLUMN "ZHANG_DM1"."GROUP_CAPACITY"."MAX_HISTORY_COUNT" IS '最大变更历史数量';
COMMENT ON COLUMN "ZHANG_DM1"."GROUP_CAPACITY"."GMT_CREATE" IS '创建时间';
COMMENT ON COLUMN "ZHANG_DM1"."GROUP_CAPACITY"."GMT_MODIFIED" IS '修改时间';


CREATE TABLE "ZHANG_DM1"."HIS_CONFIG_INFO"
(
    "ID" INT NOT NULL,
    "NID" INT IDENTITY(1, 1) NOT NULL,
    "DATA_ID" NVARCHAR2(255 CHAR) NOT NULL,
    "GROUP_ID" NVARCHAR2(128 CHAR) NOT NULL,
    "APP_NAME" NVARCHAR2(128 CHAR),
    "CONTENT" TEXT NOT NULL,
    "MD5" NVARCHAR2(32 CHAR),
    "GMT_CREATE" DATE DEFAULT SYSDATE() NOT NULL,
    "GMT_MODIFIED" DATE DEFAULT SYSDATE() NOT NULL,
    "SRC_USER" TEXT,
    "SRC_IP" NVARCHAR2(50 CHAR),
    "OP_TYPE" NCHAR(10),
    "TENANT_ID" NVARCHAR2(128 CHAR),
    "ENCRYPTED_DATA_KEY"  varchar(1024) DEFAULT '' NOT NULL,
    NOT CLUSTER PRIMARY KEY("NID"))

    STORAGE(ON "MAIN", CLUSTERBTR) ;

COMMENT ON TABLE "ZHANG_DM1"."HIS_CONFIG_INFO" IS '多租户改造';
COMMENT ON COLUMN "ZHANG_DM1"."HIS_CONFIG_INFO"."APP_NAME" IS 'app_name';
COMMENT ON COLUMN "ZHANG_DM1"."HIS_CONFIG_INFO"."TENANT_ID" IS '租户字段';
COMMENT ON COLUMN "ZHANG_DM1"."HIS_CONFIG_INFO"."ENCRYPTED_DATA_KEY" IS '秘钥';


CREATE TABLE "ZHANG_DM1"."PERMISSIONS"
(
   -- "ID" INT IDENTITY(1, 1) NOT NULL,
    "ROLE" VARCHAR2(50),
    "RESOURCE" VARCHAR2(255),
    "ACTION" VARCHAR2(8),
    NOT CLUSTER PRIMARY KEY("ID"))
    STORAGE(ON "MAIN", CLUSTERBTR) ;
CREATE UNIQUE  INDEX "uk_role_permission" ON "ZHANG_DM1"."PERMISSIONS"("role" ,"resource" ,"action") STORAGE(CLUSTERBTR) ;

CREATE TABLE "ZHANG_DM1"."ROLES"
(
 --   "ID" INT IDENTITY(1, 1) NOT NULL,
    "USERNAME" NVARCHAR2(50 CHAR) NOT NULL,
    "ROLE" NVARCHAR2(50 CHAR) NOT NULL
        NOT CLUSTER PRIMARY KEY("ID")),
	STORAGE(ON "MAIN", CLUSTERBTR) ;

CREATE UNIQUE  INDEX "idx_user_role" ON "ZHANG_DM1"."ROLES"("USERNAME" ASC,"ROLE" ASC) STORAGE(CLUSTERBTR) ;
CREATE TABLE "ZHANG_DM1"."TENANT_CAPACITY"
(
    "ID" INT IDENTITY(1, 1) NOT NULL,
    "TENANT_ID" NVARCHAR2(128 CHAR) NOT NULL,
    "QUOTA" NUMBER(11,0) NOT NULL,
    "USAGE" NUMBER(11,0) NOT NULL,
    "MAX_SIZE" NUMBER(11,0) NOT NULL,
    "MAX_AGGR_COUNT" NUMBER(11,0) NOT NULL,
    "MAX_AGGR_SIZE" NUMBER(11,0) NOT NULL,
    "MAX_HISTORY_COUNT" NUMBER(11,0) NOT NULL,
    "GMT_CREATE" DATE NOT NULL,
    "GMT_MODIFIED" DATE NOT NULL,
    NOT CLUSTER PRIMARY KEY("ID")) STORAGE(ON "MAIN", CLUSTERBTR) ;

COMMENT ON TABLE "ZHANG_DM1"."TENANT_CAPACITY" IS '租户容量信息表';
COMMENT ON COLUMN "ZHANG_DM1"."TENANT_CAPACITY"."ID" IS '主键ID';
COMMENT ON COLUMN "ZHANG_DM1"."TENANT_CAPACITY"."TENANT_ID" IS 'Tenant ID';
COMMENT ON COLUMN "ZHANG_DM1"."TENANT_CAPACITY"."QUOTA" IS '配额，0表示使用默认值';
COMMENT ON COLUMN "ZHANG_DM1"."TENANT_CAPACITY"."USAGE" IS '使用量';
COMMENT ON COLUMN "ZHANG_DM1"."TENANT_CAPACITY"."MAX_SIZE" IS '单个配置大小上限，单位为字节，0表示使用默认值';
COMMENT ON COLUMN "ZHANG_DM1"."TENANT_CAPACITY"."MAX_AGGR_COUNT" IS '聚合子配置最大个数';
COMMENT ON COLUMN "ZHANG_DM1"."TENANT_CAPACITY"."MAX_AGGR_SIZE" IS '单个聚合数据的子配置大小上限，单位为字节，0表示使用默认值';
COMMENT ON COLUMN "ZHANG_DM1"."TENANT_CAPACITY"."MAX_HISTORY_COUNT" IS '最大变更历史数量';
COMMENT ON COLUMN "ZHANG_DM1"."TENANT_CAPACITY"."GMT_CREATE" IS '创建时间';
COMMENT ON COLUMN "ZHANG_DM1"."TENANT_CAPACITY"."GMT_MODIFIED" IS '修改时间';


CREATE TABLE "ZHANG_DM1"."TENANT_INFO"
(
    "ID" INT IDENTITY(1, 1) NOT NULL,
    "KP" NVARCHAR2(128 CHAR) NOT NULL,
    "TENANT_ID" NVARCHAR2(128 CHAR),
    "TENANT_NAME" NVARCHAR2(128 CHAR),
    "TENANT_DESC" NVARCHAR2(256 CHAR),
    "CREATE_SOURCE" NVARCHAR2(32 CHAR),
    "GMT_CREATE" NUMBER(20,0) NOT NULL,
    "GMT_MODIFIED" NUMBER(20,0) NOT NULL,
    NOT CLUSTER PRIMARY KEY("ID")) STORAGE(ON "MAIN", CLUSTERBTR) ;

COMMENT ON TABLE "ZHANG_DM1"."TENANT_INFO" IS 'tenant_info';
COMMENT ON COLUMN "ZHANG_DM1"."TENANT_INFO"."ID" IS 'id';
COMMENT ON COLUMN "ZHANG_DM1"."TENANT_INFO"."KP" IS 'kp';
COMMENT ON COLUMN "ZHANG_DM1"."TENANT_INFO"."TENANT_ID" IS 'tenant_id';
COMMENT ON COLUMN "ZHANG_DM1"."TENANT_INFO"."TENANT_NAME" IS 'tenant_name';
COMMENT ON COLUMN "ZHANG_DM1"."TENANT_INFO"."TENANT_DESC" IS 'tenant_desc';
COMMENT ON COLUMN "ZHANG_DM1"."TENANT_INFO"."CREATE_SOURCE" IS 'create_source';
COMMENT ON COLUMN "ZHANG_DM1"."TENANT_INFO"."GMT_CREATE" IS '创建时间';
COMMENT ON COLUMN "ZHANG_DM1"."TENANT_INFO"."GMT_MODIFIED" IS '修改时间';


CREATE TABLE "ZHANG_DM1"."USERS"
(
   -- "ID" BIGINT IDENTITY(1, 1)  NOT NULL,
    "USERNAME" VARCHAR2(50) NOT NULL,
    "PASSWORD" VARCHAR2(500) NOT NULL,
    "ENABLED" NUMBER(1,0) NOT NULL,
    NOT CLUSTER PRIMARY KEY("ID")) STORAGE(ON "MAIN", CLUSTERBTR) ;

--INSERT INTO "USERS" VALUES ('nacos', '$2a$10$EuWPZHzz32dJN7jexM34MOeYirDdFAZm2kuWj7VEOJhhZkDrxfvUu', '1');
--INSERT INTO "ROLES" VALUES ('nacos', 'ROLE_ADMIN');

