/*
 * Copyright 1999-2018 Alibaba Group Holding Ltd.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
/*
 NAVICAT PREMIUM DATA TRANSFER

 SOURCE SERVER         : 192.168.2.179DATABLAU_NACOS
 SOURCE SERVER TYPE    : ORACLE
 SOURCE SERVER VERSION : 120100
 SOURCE HOST           : 192.168.2.179:1521
 SOURCE SCHEMA         : DATABLAU_NACOS

 TARGET SERVER TYPE    : ORACLE
 TARGET SERVER VERSION : 120100
 FILE ENCODING         : 65001

 DATE: 23/07/2024 15:36:13
*/


-- ----------------------------
-- TABLE STRUCTURE FOR CONFIG_INFO
-- ----------------------------
--DROP TABLE IF EXISTS "DATABLAU_NACOS"."CONFIG_INFO";
CREATE TABLE "DATABLAU_NACOS"."CONFIG_INFO" (
                                                "ID" NUMBER(20,0) VISIBLE NOT NULL,
                                                "DATA_ID" VARCHAR2(255 BYTE) VISIBLE NOT NULL,
                                                "GROUP_ID" VARCHAR2(128 BYTE) VISIBLE DEFAULT NULL,
                                                "CONTENT" CLOB VISIBLE NOT NULL,
                                                "MD5" VARCHAR2(32 BYTE) VISIBLE DEFAULT NULL,
                                                "GMT_CREATE" TIMESTAMP(6) VISIBLE ,
                                                "GMT_MODIFIED" TIMESTAMP(6) VISIBLE ,
                                                "SRC_USER" CLOB VISIBLE DEFAULT NULL,
                                                "SRC_IP" VARCHAR2(50 BYTE) VISIBLE DEFAULT NULL,
                                                "APP_NAME" VARCHAR2(128 BYTE) VISIBLE DEFAULT NULL,
                                                "TENANT_ID" VARCHAR2(128 BYTE) VISIBLE DEFAULT '',
                                                "C_DESC" VARCHAR2(256 BYTE) VISIBLE DEFAULT NULL,
                                                "C_USE" VARCHAR2(64 BYTE) VISIBLE DEFAULT NULL,
                                                "EFFECT" VARCHAR2(64 BYTE) VISIBLE DEFAULT NULL,
                                                "TYPE" VARCHAR2(64 BYTE) VISIBLE DEFAULT NULL,
                                                "C_SCHEMA" CLOB VISIBLE,
                                                "ENCRYPTED_DATA_KEY" VARCHAR2(1024 BYTE) VISIBLE DEFAULT ''
)
    LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536
  NEXT 1048576
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;
COMMENT ON COLUMN "DATABLAU_NACOS"."CONFIG_INFO"."ID" IS 'ID';
COMMENT ON COLUMN "DATABLAU_NACOS"."CONFIG_INFO"."DATA_ID" IS 'DATA_ID';
COMMENT ON COLUMN "DATABLAU_NACOS"."CONFIG_INFO"."GROUP_ID" IS 'GROUP_ID';
COMMENT ON COLUMN "DATABLAU_NACOS"."CONFIG_INFO"."CONTENT" IS 'CONTENT';
COMMENT ON COLUMN "DATABLAU_NACOS"."CONFIG_INFO"."MD5" IS 'MD5';
COMMENT ON COLUMN "DATABLAU_NACOS"."CONFIG_INFO"."GMT_CREATE" IS '创建时间';
COMMENT ON COLUMN "DATABLAU_NACOS"."CONFIG_INFO"."GMT_MODIFIED" IS '修改时间';
COMMENT ON COLUMN "DATABLAU_NACOS"."CONFIG_INFO"."SRC_USER" IS 'SOURCE USER';
COMMENT ON COLUMN "DATABLAU_NACOS"."CONFIG_INFO"."SRC_IP" IS 'SOURCE IP';
COMMENT ON COLUMN "DATABLAU_NACOS"."CONFIG_INFO"."APP_NAME" IS 'APP_NAME';
COMMENT ON COLUMN "DATABLAU_NACOS"."CONFIG_INFO"."TENANT_ID" IS '租户字段';
COMMENT ON COLUMN "DATABLAU_NACOS"."CONFIG_INFO"."C_DESC" IS 'CONFIGURATION DESCRIPTION';
COMMENT ON COLUMN "DATABLAU_NACOS"."CONFIG_INFO"."C_USE" IS 'CONFIGURATION USAGE';
COMMENT ON COLUMN "DATABLAU_NACOS"."CONFIG_INFO"."EFFECT" IS '配置生效的描述';
COMMENT ON COLUMN "DATABLAU_NACOS"."CONFIG_INFO"."TYPE" IS '配置的类型';
COMMENT ON COLUMN "DATABLAU_NACOS"."CONFIG_INFO"."C_SCHEMA" IS '配置的模式';
COMMENT ON COLUMN "DATABLAU_NACOS"."CONFIG_INFO"."ENCRYPTED_DATA_KEY" IS '密钥';
CREATE SEQUENCE config_info_info_id_seq
    START WITH 1
    INCREMENT BY 1
    MINVALUE 1
    MAXVALUE 999999999999999999
    CACHE 20;

ALTER TABLE DATABLAU_NACOS.CONFIG_INFO
    MODIFY ID DEFAULT config_info_info_id_seq.NEXTVAL;
-- ----------------------------
-- TABLE STRUCTURE FOR CONFIG_INFO_AGGR
-- ----------------------------
--DROP TABLE IF EXISTS "DATABLAU_NACOS"."CONFIG_INFO_AGGR";
CREATE TABLE "DATABLAU_NACOS"."CONFIG_INFO_AGGR" (
                                                     "ID" NUMBER(20,0) VISIBLE NOT NULL,
                                                     "DATA_ID" VARCHAR2(255 BYTE) VISIBLE NOT NULL,
                                                     "GROUP_ID" VARCHAR2(128 BYTE) VISIBLE DEFAULT NULL NOT NULL,
                                                     "CONTENT" CLOB VISIBLE NOT NULL,
                                                     "GMT_MODIFIED" TIMESTAMP(6) VISIBLE NOT NULL,
                                                     "APP_NAME" VARCHAR2(128 BYTE) VISIBLE DEFAULT NULL,
                                                     "TENANT_ID" VARCHAR2(128 BYTE) VISIBLE DEFAULT '',
                                                     "DATUM_ID" VARCHAR2(255 BYTE) VISIBLE NOT NULL
)
    LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536
  NEXT 1048576
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;
COMMENT ON COLUMN "DATABLAU_NACOS"."CONFIG_INFO_AGGR"."ID" IS 'ID';
COMMENT ON COLUMN "DATABLAU_NACOS"."CONFIG_INFO_AGGR"."DATA_ID" IS 'DATA_ID';
COMMENT ON COLUMN "DATABLAU_NACOS"."CONFIG_INFO_AGGR"."GROUP_ID" IS 'GROUP_ID';
COMMENT ON COLUMN "DATABLAU_NACOS"."CONFIG_INFO_AGGR"."CONTENT" IS '内容';
COMMENT ON COLUMN "DATABLAU_NACOS"."CONFIG_INFO_AGGR"."GMT_MODIFIED" IS '修改时间';
COMMENT ON COLUMN "DATABLAU_NACOS"."CONFIG_INFO_AGGR"."APP_NAME" IS 'APP_NAME';
COMMENT ON COLUMN "DATABLAU_NACOS"."CONFIG_INFO_AGGR"."TENANT_ID" IS '租户字段';
COMMENT ON COLUMN "DATABLAU_NACOS"."CONFIG_INFO_AGGR"."DATUM_ID" IS 'DATUM_ID';
CREATE SEQUENCE config_info_aggr_id_seq
    START WITH 1
    INCREMENT BY 1
    MINVALUE 1
    MAXVALUE 999999999999999999
    CACHE 20;

ALTER TABLE DATABLAU_NACOS.CONFIG_INFO_AGGR
    MODIFY ID DEFAULT config_info_aggr_id_seq.NEXTVAL;
-- ----------------------------
-- TABLE STRUCTURE FOR CONFIG_INFO_BETA
-- ----------------------------
--DROP TABLE IF EXISTS "DATABLAU_NACOS"."CONFIG_INFO_BETA";
CREATE TABLE "DATABLAU_NACOS"."CONFIG_INFO_BETA" (
                                                     "ID" NUMBER(20,0) VISIBLE NOT NULL,
                                                     "DATA_ID" VARCHAR2(255 BYTE) VISIBLE NOT NULL,
                                                     "GROUP_ID" VARCHAR2(128 BYTE) VISIBLE DEFAULT NULL NOT NULL,
                                                     "CONTENT" CLOB VISIBLE DEFAULT NULL NOT NULL,
                                                     "MD5" VARCHAR2(32 BYTE) VISIBLE DEFAULT NULL,
                                                     "GMT_CREATE" TIMESTAMP(6) VISIBLE NOT NULL,
                                                     "GMT_MODIFIED" TIMESTAMP(6) VISIBLE NOT NULL,
                                                     "SRC_USER" CLOB VISIBLE DEFAULT NULL,
                                                     "SRC_IP" VARCHAR2(50 BYTE) VISIBLE DEFAULT NULL,
                                                     "APP_NAME" VARCHAR2(128 BYTE) VISIBLE DEFAULT NULL,
                                                     "TENANT_ID" VARCHAR2(128 BYTE) VISIBLE DEFAULT '',
                                                     "ENCRYPTED_DATA_KEY" VARCHAR2(1024 BYTE) VISIBLE DEFAULT '',
                                                     "BETA_IPS" VARCHAR2(1024 BYTE) VISIBLE DEFAULT NULL
)
    LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536
  NEXT 1048576
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;
COMMENT ON COLUMN "DATABLAU_NACOS"."CONFIG_INFO_BETA"."ID" IS 'ID';
COMMENT ON COLUMN "DATABLAU_NACOS"."CONFIG_INFO_BETA"."DATA_ID" IS 'DATA_ID';
COMMENT ON COLUMN "DATABLAU_NACOS"."CONFIG_INFO_BETA"."GROUP_ID" IS 'GROUP_ID';
COMMENT ON COLUMN "DATABLAU_NACOS"."CONFIG_INFO_BETA"."CONTENT" IS 'CONTENT';
COMMENT ON COLUMN "DATABLAU_NACOS"."CONFIG_INFO_BETA"."MD5" IS 'MD5';
COMMENT ON COLUMN "DATABLAU_NACOS"."CONFIG_INFO_BETA"."GMT_CREATE" IS '创建时间';
COMMENT ON COLUMN "DATABLAU_NACOS"."CONFIG_INFO_BETA"."GMT_MODIFIED" IS '修改时间';
COMMENT ON COLUMN "DATABLAU_NACOS"."CONFIG_INFO_BETA"."SRC_USER" IS 'SOURCE USER';
COMMENT ON COLUMN "DATABLAU_NACOS"."CONFIG_INFO_BETA"."SRC_IP" IS 'SOURCE IP';
COMMENT ON COLUMN "DATABLAU_NACOS"."CONFIG_INFO_BETA"."APP_NAME" IS 'APP_NAME';
COMMENT ON COLUMN "DATABLAU_NACOS"."CONFIG_INFO_BETA"."TENANT_ID" IS '租户字段';
COMMENT ON COLUMN "DATABLAU_NACOS"."CONFIG_INFO_BETA"."ENCRYPTED_DATA_KEY" IS '密钥';
COMMENT ON COLUMN "DATABLAU_NACOS"."CONFIG_INFO_BETA"."BETA_IPS" IS 'BETA_IPS';
CREATE SEQUENCE config_info_beta_id_seq
    START WITH 1
    INCREMENT BY 1
    MINVALUE 1
    MAXVALUE 999999999999999999
    CACHE 20;

ALTER TABLE DATABLAU_NACOS.CONFIG_INFO_BETA
    MODIFY ID DEFAULT config_info_beta_id_seq.NEXTVAL;
-- ----------------------------
-- TABLE STRUCTURE FOR CONFIG_INFO_TAG
-- ----------------------------
--DROP TABLE IF EXISTS "DATABLAU_NACOS"."CONFIG_INFO_TAG";
CREATE TABLE "DATABLAU_NACOS"."CONFIG_INFO_TAG" (
                                                    "ID" NUMBER(20,0) VISIBLE NOT NULL,
                                                    "DATA_ID" VARCHAR2(255 BYTE) VISIBLE NOT NULL,
                                                    "GROUP_ID" VARCHAR2(128 BYTE) VISIBLE DEFAULT NULL NOT NULL,
                                                    "CONTENT" CLOB VISIBLE DEFAULT NULL NOT NULL,
                                                    "MD5" VARCHAR2(32 BYTE) VISIBLE DEFAULT NULL,
                                                    "GMT_CREATE" TIMESTAMP(6) VISIBLE ,
                                                    "GMT_MODIFIED" TIMESTAMP(6) VISIBLE ,
                                                    "SRC_USER" CLOB VISIBLE DEFAULT NULL,
                                                    "SRC_IP" VARCHAR2(50 BYTE) VISIBLE DEFAULT NULL,
                                                    "APP_NAME" VARCHAR2(128 BYTE) VISIBLE DEFAULT NULL,
                                                    "TENANT_ID" VARCHAR2(128 BYTE) VISIBLE DEFAULT '',
                                                    "TAG_ID" VARCHAR2(128 BYTE) VISIBLE
)
    LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536
  NEXT 1048576
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;
COMMENT ON COLUMN "DATABLAU_NACOS"."CONFIG_INFO_TAG"."ID" IS 'ID';
COMMENT ON COLUMN "DATABLAU_NACOS"."CONFIG_INFO_TAG"."DATA_ID" IS 'DATA_ID';
COMMENT ON COLUMN "DATABLAU_NACOS"."CONFIG_INFO_TAG"."GROUP_ID" IS 'GROUP_ID';
COMMENT ON COLUMN "DATABLAU_NACOS"."CONFIG_INFO_TAG"."CONTENT" IS 'CONTENT';
COMMENT ON COLUMN "DATABLAU_NACOS"."CONFIG_INFO_TAG"."MD5" IS 'MD5';
COMMENT ON COLUMN "DATABLAU_NACOS"."CONFIG_INFO_TAG"."GMT_CREATE" IS '创建时间';
COMMENT ON COLUMN "DATABLAU_NACOS"."CONFIG_INFO_TAG"."GMT_MODIFIED" IS '修改时间';
COMMENT ON COLUMN "DATABLAU_NACOS"."CONFIG_INFO_TAG"."SRC_USER" IS 'SOURCE USER';
COMMENT ON COLUMN "DATABLAU_NACOS"."CONFIG_INFO_TAG"."SRC_IP" IS 'SOURCE IP';
COMMENT ON COLUMN "DATABLAU_NACOS"."CONFIG_INFO_TAG"."APP_NAME" IS 'APP_NAME';
COMMENT ON COLUMN "DATABLAU_NACOS"."CONFIG_INFO_TAG"."TENANT_ID" IS '租户字段';
COMMENT ON COLUMN "DATABLAU_NACOS"."CONFIG_INFO_TAG"."TAG_ID" IS 'TAG_ID';
CREATE SEQUENCE config_info_tag_id_seq
    START WITH 1
    INCREMENT BY 1
    MINVALUE 1
    MAXVALUE 999999999999999999
    CACHE 20;

ALTER TABLE DATABLAU_NACOS.CONFIG_INFO_TAG
    MODIFY ID DEFAULT config_info_tag_id_seq.NEXTVAL;
-- ----------------------------
-- TABLE STRUCTURE FOR CONFIG_TAGS_RELATION
-- ----------------------------
--DROP TABLE IF EXISTS "DATABLAU_NACOS"."CONFIG_TAGS_RELATION";
CREATE TABLE "DATABLAU_NACOS"."CONFIG_TAGS_RELATION" (
                                                         "ID" NUMBER(20,0) VISIBLE NOT NULL,
                                                         "DATA_ID" VARCHAR2(255 BYTE) VISIBLE NOT NULL,
                                                         "GROUP_ID" VARCHAR2(128 BYTE) VISIBLE DEFAULT NULL NOT NULL,
                                                         "TENANT_ID" VARCHAR2(128 BYTE) VISIBLE DEFAULT '',
                                                         "TAG_NAME" VARCHAR2(128 BYTE) VISIBLE NOT NULL,
                                                         "TAG_TYPE" VARCHAR2(64 BYTE) VISIBLE DEFAULT NULL,
                                                         "NID" NUMBER(20,0) VISIBLE NOT NULL
)
    LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536
  NEXT 1048576
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;
COMMENT ON COLUMN "DATABLAU_NACOS"."CONFIG_TAGS_RELATION"."ID" IS 'ID';
COMMENT ON COLUMN "DATABLAU_NACOS"."CONFIG_TAGS_RELATION"."DATA_ID" IS 'DATA_ID';
COMMENT ON COLUMN "DATABLAU_NACOS"."CONFIG_TAGS_RELATION"."GROUP_ID" IS 'GROUP_ID';
COMMENT ON COLUMN "DATABLAU_NACOS"."CONFIG_TAGS_RELATION"."TENANT_ID" IS '租户字段';
COMMENT ON COLUMN "DATABLAU_NACOS"."CONFIG_TAGS_RELATION"."TAG_NAME" IS 'TAG_NAME';
COMMENT ON COLUMN "DATABLAU_NACOS"."CONFIG_TAGS_RELATION"."TAG_TYPE" IS 'TAG_TYPE';
COMMENT ON COLUMN "DATABLAU_NACOS"."CONFIG_TAGS_RELATION"."NID" IS 'NID, 自增长标识NID';
CREATE SEQUENCE config_tags_relation_id_seq
    START WITH 1
    INCREMENT BY 1
    MINVALUE 1
    MAXVALUE 999999999999999999
    CACHE 20;

ALTER TABLE DATABLAU_NACOS.CONFIG_TAGS_RELATION
    MODIFY ID DEFAULT config_tags_relation_id_seq.NEXTVAL;


-- ----------------------------
-- TABLE STRUCTURE FOR GROUP_CAPACITY
-- ----------------------------
--DROP TABLE IF EXISTS "DATABLAU_NACOS"."GROUP_CAPACITY";
CREATE TABLE "DATABLAU_NACOS"."GROUP_CAPACITY" (
                                                   "ID" NUMBER(20,0) VISIBLE NOT NULL,
                                                   "GROUP_ID" VARCHAR2(128 BYTE) VISIBLE DEFAULT '' NOT NULL,
                                                   "QUOTA" NUMBER(10,0) VISIBLE DEFAULT 0 NOT NULL,
                                                   "USAGE" NUMBER(10,0) VISIBLE DEFAULT 0 NOT NULL,
                                                   "MAX_SIZE" NUMBER(10,0) VISIBLE DEFAULT 0 NOT NULL,
                                                   "MAX_AGGR_COUNT" NUMBER(10,0) VISIBLE DEFAULT 0 NOT NULL,
                                                   "MAX_AGGR_SIZE" NUMBER(10,0) VISIBLE DEFAULT 0 NOT NULL,
                                                   "MAX_HISTORY_COUNT" NUMBER(10,0) VISIBLE DEFAULT 0 NOT NULL,
                                                   "GMT_CREATE" TIMESTAMP(6) VISIBLE NOT NULL,
                                                   "GMT_MODIFIED" TIMESTAMP(6) VISIBLE NOT NULL
)
    LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536
  NEXT 1048576
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;
COMMENT ON COLUMN "DATABLAU_NACOS"."GROUP_CAPACITY"."ID" IS '主键ID';
COMMENT ON COLUMN "DATABLAU_NACOS"."GROUP_CAPACITY"."GROUP_ID" IS 'GROUP ID，空字符表示整个集群';
COMMENT ON COLUMN "DATABLAU_NACOS"."GROUP_CAPACITY"."QUOTA" IS '配额，0表示使用默认值';
COMMENT ON COLUMN "DATABLAU_NACOS"."GROUP_CAPACITY"."USAGE" IS '使用量';
COMMENT ON COLUMN "DATABLAU_NACOS"."GROUP_CAPACITY"."MAX_SIZE" IS '单个配置大小上限，单位为字节，0表示使用默认值';
COMMENT ON COLUMN "DATABLAU_NACOS"."GROUP_CAPACITY"."MAX_AGGR_COUNT" IS '聚合子配置最大个数，，0表示使用默认值';
COMMENT ON COLUMN "DATABLAU_NACOS"."GROUP_CAPACITY"."MAX_AGGR_SIZE" IS '单个聚合数据的子配置大小上限，单位为字节，0表示使用默认值';
COMMENT ON COLUMN "DATABLAU_NACOS"."GROUP_CAPACITY"."MAX_HISTORY_COUNT" IS '最大变更历史数量';
COMMENT ON COLUMN "DATABLAU_NACOS"."GROUP_CAPACITY"."GMT_CREATE" IS '创建时间';
CREATE SEQUENCE group_capacity_id_seq
    START WITH 1
    INCREMENT BY 1
    MINVALUE 1
    MAXVALUE 999999999999999999
    CACHE 20;

ALTER TABLE DATABLAU_NACOS.GROUP_CAPACITY
    MODIFY ID DEFAULT group_capacity_id_seq.NEXTVAL;
-- ----------------------------
-- TABLE STRUCTURE FOR HIS_CONFIG_INFO
-- ----------------------------
--DROP TABLE IF EXISTS "DATABLAU_NACOS"."HIS_CONFIG_INFO";
CREATE TABLE "DATABLAU_NACOS"."HIS_CONFIG_INFO" (
                                                    "ID" NUMBER(20,0) VISIBLE NOT NULL,
                                                    "DATA_ID" VARCHAR2(255 BYTE) VISIBLE NOT NULL,
                                                    "GROUP_ID" VARCHAR2(128 BYTE) VISIBLE DEFAULT NULL NOT NULL,
                                                    "CONTENT" CLOB VISIBLE DEFAULT NULL NOT NULL,
                                                    "MD5" VARCHAR2(32 BYTE) VISIBLE DEFAULT NULL,
                                                    "GMT_CREATE" TIMESTAMP(6) VISIBLE ,
                                                    "GMT_MODIFIED" TIMESTAMP(6) VISIBLE ,
                                                    "SRC_USER" CLOB VISIBLE DEFAULT NULL,
                                                    "SRC_IP" VARCHAR2(50 BYTE) VISIBLE DEFAULT NULL,
                                                    "APP_NAME" VARCHAR2(128 BYTE) VISIBLE DEFAULT NULL,
                                                    "TENANT_ID" VARCHAR2(128 BYTE) VISIBLE DEFAULT '',
                                                    "NID" NUMBER(20,0) VISIBLE NOT NULL,
                                                    "OP_TYPE" VARCHAR2(10 BYTE) VISIBLE,
                                                    "ENCRYPTED_DATA_KEY" VARCHAR2(1024 BYTE) VISIBLE DEFAULT ''
)
    LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536
  NEXT 1048576
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;
COMMENT ON COLUMN "DATABLAU_NACOS"."HIS_CONFIG_INFO"."ID" IS 'ID';
COMMENT ON COLUMN "DATABLAU_NACOS"."HIS_CONFIG_INFO"."DATA_ID" IS 'DATA_ID';
COMMENT ON COLUMN "DATABLAU_NACOS"."HIS_CONFIG_INFO"."GROUP_ID" IS 'GROUP_ID';
COMMENT ON COLUMN "DATABLAU_NACOS"."HIS_CONFIG_INFO"."CONTENT" IS 'CONTENT';
COMMENT ON COLUMN "DATABLAU_NACOS"."HIS_CONFIG_INFO"."MD5" IS 'MD5';
COMMENT ON COLUMN "DATABLAU_NACOS"."HIS_CONFIG_INFO"."GMT_CREATE" IS '创建时间';
COMMENT ON COLUMN "DATABLAU_NACOS"."HIS_CONFIG_INFO"."GMT_MODIFIED" IS '修改时间';
COMMENT ON COLUMN "DATABLAU_NACOS"."HIS_CONFIG_INFO"."SRC_USER" IS 'SOURCE USER';
COMMENT ON COLUMN "DATABLAU_NACOS"."HIS_CONFIG_INFO"."SRC_IP" IS 'SOURCE IP';
COMMENT ON COLUMN "DATABLAU_NACOS"."HIS_CONFIG_INFO"."APP_NAME" IS 'APP_NAME';
COMMENT ON COLUMN "DATABLAU_NACOS"."HIS_CONFIG_INFO"."TENANT_ID" IS '租户字段';
COMMENT ON COLUMN "DATABLAU_NACOS"."HIS_CONFIG_INFO"."NID" IS 'NID, 自增标识';
COMMENT ON COLUMN "DATABLAU_NACOS"."HIS_CONFIG_INFO"."OP_TYPE" IS 'OPERATION TYPE';
COMMENT ON COLUMN "DATABLAU_NACOS"."HIS_CONFIG_INFO"."ENCRYPTED_DATA_KEY" IS '密钥';
CREATE SEQUENCE his_config_info_id_seq
    START WITH 1
    INCREMENT BY 1
    MINVALUE 1
    MAXVALUE 999999999999999999
    CACHE 20;

ALTER TABLE DATABLAU_NACOS.HIS_CONFIG_INFO
    MODIFY ID DEFAULT his_config_info_id_seq.NEXTVAL;

CREATE SEQUENCE his_config_info_nid_seq
    START WITH 1
    INCREMENT BY 1
    MINVALUE 1
    MAXVALUE 999999999999999999
    CACHE 20;

ALTER TABLE DATABLAU_NACOS.HIS_CONFIG_INFO
    MODIFY NID DEFAULT his_config_info_nid_seq.NEXTVAL;
-- ----------------------------
-- TABLE STRUCTURE FOR PERMISSIONS
-- ----------------------------
--DROP TABLE IF EXISTS "DATABLAU_NACOS"."PERMISSIONS";
CREATE TABLE "DATABLAU_NACOS"."PERMISSIONS" (
    --    "ID" NUMBER(20,0) VISIBLE NOT NULL,
                                                "ROLE" VARCHAR2(50 BYTE) VISIBLE,
                                                "RESOURCE" VARCHAR2(128 BYTE) VISIBLE,
                                                "ACTION" VARCHAR2(8 BYTE) VISIBLE
)
    LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536
  NEXT 1048576
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;

-- ----------------------------
-- TABLE STRUCTURE FOR ROLES
-- ----------------------------
--DROP TABLE IF EXISTS "DATABLAU_NACOS"."ROLES";
CREATE TABLE "DATABLAU_NACOS"."ROLES" (
    --  "ID" NUMBER(20,0) VISIBLE NOT NULL,
                                          "USERNAME" VARCHAR2(50 BYTE) VISIBLE NOT NULL,
                                          "ROLE" VARCHAR2(50 BYTE) VISIBLE NOT NULL
)
    LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536
  NEXT 1048576
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;

-- ----------------------------
-- TABLE STRUCTURE FOR TENANT_CAPACITY
-- ----------------------------
--DROP TABLE IF EXISTS "DATABLAU_NACOS"."TENANT_CAPACITY";
CREATE TABLE "DATABLAU_NACOS"."TENANT_CAPACITY" (
                                                    "ID" NUMBER(20,0) VISIBLE NOT NULL,
                                                    "TENANT_ID" VARCHAR2(128 BYTE) VISIBLE DEFAULT '' NOT NULL,
                                                    "QUOTA" NUMBER(10,0) VISIBLE DEFAULT 0 NOT NULL,
                                                    "USAGE" NUMBER(10,0) VISIBLE DEFAULT 0 NOT NULL,
                                                    "MAX_SIZE" NUMBER(10,0) VISIBLE DEFAULT 0 NOT NULL,
                                                    "MAX_AGGR_COUNT" NUMBER(10,0) VISIBLE DEFAULT 0 NOT NULL,
                                                    "MAX_AGGR_SIZE" NUMBER(10,0) VISIBLE DEFAULT 0 NOT NULL,
                                                    "MAX_HISTORY_COUNT" NUMBER(10,0) VISIBLE DEFAULT 0 NOT NULL,
                                                    "GMT_CREATE" TIMESTAMP(6) VISIBLE NOT NULL,
                                                    "GMT_MODIFIED" TIMESTAMP(6) VISIBLE NOT NULL
)
    LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536
  NEXT 1048576
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;
COMMENT ON COLUMN "DATABLAU_NACOS"."TENANT_CAPACITY"."ID" IS '主键ID';
COMMENT ON COLUMN "DATABLAU_NACOS"."TENANT_CAPACITY"."TENANT_ID" IS 'TENANT ID';
COMMENT ON COLUMN "DATABLAU_NACOS"."TENANT_CAPACITY"."QUOTA" IS '配额，0表示使用默认值';
COMMENT ON COLUMN "DATABLAU_NACOS"."TENANT_CAPACITY"."USAGE" IS '使用量';
COMMENT ON COLUMN "DATABLAU_NACOS"."TENANT_CAPACITY"."MAX_SIZE" IS '单个配置大小上限，单位为字节，0表示使用默认值';
COMMENT ON COLUMN "DATABLAU_NACOS"."TENANT_CAPACITY"."MAX_AGGR_COUNT" IS '聚合子配置最大个数，，0表示使用默认值';
COMMENT ON COLUMN "DATABLAU_NACOS"."TENANT_CAPACITY"."MAX_AGGR_SIZE" IS '单个聚合数据的子配置大小上限，单位为字节，0表示使用默认值';
COMMENT ON COLUMN "DATABLAU_NACOS"."TENANT_CAPACITY"."MAX_HISTORY_COUNT" IS '最大变更历史数量';
COMMENT ON COLUMN "DATABLAU_NACOS"."TENANT_CAPACITY"."GMT_CREATE" IS '创建时间';
CREATE SEQUENCE tenant_capacity_id_seq
    START WITH 1
    INCREMENT BY 1
    MINVALUE 1
    MAXVALUE 999999999999999999
    CACHE 20;

ALTER TABLE DATABLAU_NACOS.TENANT_CAPACITY
    MODIFY ID DEFAULT tenant_capacity_id_seq.NEXTVAL;
-- ----------------------------
-- TABLE STRUCTURE FOR TENANT_INFO
-- ----------------------------
--DROP TABLE IF EXISTS "DATABLAU_NACOS"."TENANT_INFO";
CREATE TABLE "DATABLAU_NACOS"."TENANT_INFO" (
                                                "ID" NUMBER(20,0) VISIBLE NOT NULL,
                                                "KP" VARCHAR2(128 BYTE) VISIBLE NOT NULL,
                                                "TENANT_ID" VARCHAR2(128 BYTE) VISIBLE DEFAULT '',
                                                "TENANT_NAME" VARCHAR2(128 BYTE) VISIBLE DEFAULT '',
                                                "TENANT_DESC" VARCHAR2(256 BYTE) VISIBLE DEFAULT NULL,
                                                "CREATE_SOURCE" VARCHAR2(32 BYTE) VISIBLE DEFAULT NULL,
                                                "GMT_CREATE" NUMBER(20,0) VISIBLE,
                                                "GMT_MODIFIED" NUMBER(20,0) VISIBLE
)
    LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536
  NEXT 1048576
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;
COMMENT ON COLUMN "DATABLAU_NACOS"."TENANT_INFO"."ID" IS 'ID';
COMMENT ON COLUMN "DATABLAU_NACOS"."TENANT_INFO"."KP" IS 'KP';
COMMENT ON COLUMN "DATABLAU_NACOS"."TENANT_INFO"."TENANT_ID" IS 'TENANT_ID';
COMMENT ON COLUMN "DATABLAU_NACOS"."TENANT_INFO"."TENANT_NAME" IS 'TENANT_NAME';
COMMENT ON COLUMN "DATABLAU_NACOS"."TENANT_INFO"."TENANT_DESC" IS 'TENANT_DESC';
COMMENT ON COLUMN "DATABLAU_NACOS"."TENANT_INFO"."CREATE_SOURCE" IS 'CREATE_SOURCE';
COMMENT ON COLUMN "DATABLAU_NACOS"."TENANT_INFO"."GMT_CREATE" IS '创建时间';
COMMENT ON COLUMN "DATABLAU_NACOS"."TENANT_INFO"."GMT_MODIFIED" IS '修改时间';

CREATE SEQUENCE tenant_info_id_seq
    START WITH 1
    INCREMENT BY 1
    MINVALUE 1
    MAXVALUE 999999999999999999
    CACHE 20;

ALTER TABLE DATABLAU_NACOS.TENANT_INFO
    MODIFY ID DEFAULT tenant_info_id_seq.NEXTVAL;
-- ----------------------------
-- TABLE STRUCTURE FOR USERS
-- ----------------------------
--DROP TABLE IF EXISTS "DATABLAU_NACOS"."USERS";
CREATE TABLE "DATABLAU_NACOS"."USERS" (
    --      "ID" NUMBER(20,0) VISIBLE NOT NULL,
                                          "USERNAME" VARCHAR2(50 BYTE) VISIBLE NOT NULL,
                                          "PASSWORD" VARCHAR2(500 BYTE) VISIBLE NOT NULL,
                                          "ENABLED" NUMBER(1,0) VISIBLE NOT NULL
)
    LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536
  NEXT 1048576
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;

-- ----------------------------
-- SEQUENCE STRUCTURE FOR ISEQ$$_494347
-- ----------------------------
CREATE SEQUENCE "DATABLAU_NACOS"."ISEQ$$_494347" MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 CACHE 20;

-- ----------------------------
-- PRIMARY KEY STRUCTURE FOR TABLE CONFIG_INFO
-- ----------------------------
ALTER TABLE "DATABLAU_NACOS"."CONFIG_INFO" ADD CONSTRAINT "SYS_C0056605" PRIMARY KEY ("ID");

-- ----------------------------
-- CHECKS STRUCTURE FOR TABLE CONFIG_INFO
-- ----------------------------
ALTER TABLE "DATABLAU_NACOS"."CONFIG_INFO" ADD CONSTRAINT "SYS_C0056600" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "DATABLAU_NACOS"."CONFIG_INFO" ADD CONSTRAINT "SYS_C0056601" CHECK ("DATA_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "DATABLAU_NACOS"."CONFIG_INFO" ADD CONSTRAINT "SYS_C0056602" CHECK ("CONTENT" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "DATABLAU_NACOS"."CONFIG_INFO" ADD CONSTRAINT "SYS_C0056603" CHECK ("GMT_CREATE" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "DATABLAU_NACOS"."CONFIG_INFO" ADD CONSTRAINT "SYS_C0056604" CHECK ("GMT_MODIFIED" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- INDEXES STRUCTURE FOR TABLE CONFIG_INFO
-- ----------------------------
CREATE UNIQUE INDEX "DATABLAU_NACOS"."UK_CONFIGINFO"
    ON "DATABLAU_NACOS"."CONFIG_INFO" ("DATA_ID" ASC, "GROUP_ID" ASC, "TENANT_ID" ASC)
    LOGGING
  VISIBLE
PCTFREE 10
INITRANS 2
STORAGE (
  INITIAL 65536
  NEXT 1048576
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
  FLASH_CACHE DEFAULT
)
   USABLE;

-- ----------------------------
-- PRIMARY KEY STRUCTURE FOR TABLE CONFIG_INFO_AGGR
-- ----------------------------
ALTER TABLE "DATABLAU_NACOS"."CONFIG_INFO_AGGR" ADD CONSTRAINT "SYS_C0056627" PRIMARY KEY ("ID");

-- ----------------------------
-- CHECKS STRUCTURE FOR TABLE CONFIG_INFO_AGGR
-- ----------------------------
ALTER TABLE "DATABLAU_NACOS"."CONFIG_INFO_AGGR" ADD CONSTRAINT "SYS_C0056617" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "DATABLAU_NACOS"."CONFIG_INFO_AGGR" ADD CONSTRAINT "SYS_C0056618" CHECK ("DATA_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "DATABLAU_NACOS"."CONFIG_INFO_AGGR" ADD CONSTRAINT "SYS_C0056619" CHECK ("CONTENT" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "DATABLAU_NACOS"."CONFIG_INFO_AGGR" ADD CONSTRAINT "SYS_C0056621" CHECK ("GMT_MODIFIED" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "DATABLAU_NACOS"."CONFIG_INFO_AGGR" ADD CONSTRAINT "SYS_C0056622" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "DATABLAU_NACOS"."CONFIG_INFO_AGGR" ADD CONSTRAINT "SYS_C0056623" CHECK ("DATA_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "DATABLAU_NACOS"."CONFIG_INFO_AGGR" ADD CONSTRAINT "SYS_C0056624" CHECK ("CONTENT" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "DATABLAU_NACOS"."CONFIG_INFO_AGGR" ADD CONSTRAINT "SYS_C0056626" CHECK ("GMT_MODIFIED" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "DATABLAU_NACOS"."CONFIG_INFO_AGGR" ADD CONSTRAINT "SYS_C0056628" CHECK ("GROUP_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "DATABLAU_NACOS"."CONFIG_INFO_AGGR" ADD CONSTRAINT "SYS_C0056629" CHECK ("DATUM_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- INDEXES STRUCTURE FOR TABLE CONFIG_INFO_AGGR
-- ----------------------------
CREATE UNIQUE INDEX "DATABLAU_NACOS"."UK_CONFIG_INFO_AGGR"
    ON "DATABLAU_NACOS"."CONFIG_INFO_AGGR" ("DATA_ID" ASC, "GROUP_ID" ASC, "TENANT_ID" ASC, "DATUM_ID" ASC)
    LOGGING
  VISIBLE
PCTFREE 10
INITRANS 2
STORAGE (
  INITIAL 65536
  NEXT 1048576
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
  FLASH_CACHE DEFAULT
)
   USABLE;

-- ----------------------------
-- PRIMARY KEY STRUCTURE FOR TABLE CONFIG_INFO_BETA
-- ----------------------------
ALTER TABLE "DATABLAU_NACOS"."CONFIG_INFO_BETA" ADD CONSTRAINT "SYS_C0056651" PRIMARY KEY ("ID");

-- ----------------------------
-- CHECKS STRUCTURE FOR TABLE CONFIG_INFO_BETA
-- ----------------------------
ALTER TABLE "DATABLAU_NACOS"."CONFIG_INFO_BETA" ADD CONSTRAINT "SYS_C0056641" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "DATABLAU_NACOS"."CONFIG_INFO_BETA" ADD CONSTRAINT "SYS_C0056642" CHECK ("DATA_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "DATABLAU_NACOS"."CONFIG_INFO_BETA" ADD CONSTRAINT "SYS_C0056643" CHECK ("CONTENT" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "DATABLAU_NACOS"."CONFIG_INFO_BETA" ADD CONSTRAINT "SYS_C0056644" CHECK ("GMT_CREATE" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "DATABLAU_NACOS"."CONFIG_INFO_BETA" ADD CONSTRAINT "SYS_C0056645" CHECK ("GMT_MODIFIED" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "DATABLAU_NACOS"."CONFIG_INFO_BETA" ADD CONSTRAINT "SYS_C0056646" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "DATABLAU_NACOS"."CONFIG_INFO_BETA" ADD CONSTRAINT "SYS_C0056647" CHECK ("DATA_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "DATABLAU_NACOS"."CONFIG_INFO_BETA" ADD CONSTRAINT "SYS_C0056648" CHECK ("CONTENT" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "DATABLAU_NACOS"."CONFIG_INFO_BETA" ADD CONSTRAINT "SYS_C0056649" CHECK ("GMT_CREATE" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "DATABLAU_NACOS"."CONFIG_INFO_BETA" ADD CONSTRAINT "SYS_C0056650" CHECK ("GMT_MODIFIED" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "DATABLAU_NACOS"."CONFIG_INFO_BETA" ADD CONSTRAINT "SYS_C0056653" CHECK ("GROUP_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- INDEXES STRUCTURE FOR TABLE CONFIG_INFO_BETA
-- ----------------------------
CREATE UNIQUE INDEX "DATABLAU_NACOS"."UK_CONFIG_INFO_BETA"
    ON "DATABLAU_NACOS"."CONFIG_INFO_BETA" ("DATA_ID" ASC, "GROUP_ID" ASC, "TENANT_ID" ASC)
    LOGGING
  VISIBLE
PCTFREE 10
INITRANS 2
STORAGE (
  INITIAL 65536
  NEXT 1048576
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
  FLASH_CACHE DEFAULT
)
   USABLE;

-- ----------------------------
-- PRIMARY KEY STRUCTURE FOR TABLE CONFIG_INFO_TAG
-- ----------------------------
ALTER TABLE "DATABLAU_NACOS"."CONFIG_INFO_TAG" ADD CONSTRAINT "SYS_C0056671" PRIMARY KEY ("ID");

-- ----------------------------
-- CHECKS STRUCTURE FOR TABLE CONFIG_INFO_TAG
-- ----------------------------
ALTER TABLE "DATABLAU_NACOS"."CONFIG_INFO_TAG" ADD CONSTRAINT "SYS_C0056654" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "DATABLAU_NACOS"."CONFIG_INFO_TAG" ADD CONSTRAINT "SYS_C0056655" CHECK ("DATA_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "DATABLAU_NACOS"."CONFIG_INFO_TAG" ADD CONSTRAINT "SYS_C0056656" CHECK ("GROUP_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "DATABLAU_NACOS"."CONFIG_INFO_TAG" ADD CONSTRAINT "SYS_C0056657" CHECK ("CONTENT" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "DATABLAU_NACOS"."CONFIG_INFO_TAG" ADD CONSTRAINT "SYS_C0056658" CHECK ("GMT_CREATE" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "DATABLAU_NACOS"."CONFIG_INFO_TAG" ADD CONSTRAINT "SYS_C0056659" CHECK ("GMT_MODIFIED" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "DATABLAU_NACOS"."CONFIG_INFO_TAG" ADD CONSTRAINT "SYS_C0056660" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "DATABLAU_NACOS"."CONFIG_INFO_TAG" ADD CONSTRAINT "SYS_C0056661" CHECK ("DATA_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "DATABLAU_NACOS"."CONFIG_INFO_TAG" ADD CONSTRAINT "SYS_C0056662" CHECK ("CONTENT" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "DATABLAU_NACOS"."CONFIG_INFO_TAG" ADD CONSTRAINT "SYS_C0056663" CHECK ("GMT_CREATE" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "DATABLAU_NACOS"."CONFIG_INFO_TAG" ADD CONSTRAINT "SYS_C0056664" CHECK ("GMT_MODIFIED" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "DATABLAU_NACOS"."CONFIG_INFO_TAG" ADD CONSTRAINT "SYS_C0056665" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "DATABLAU_NACOS"."CONFIG_INFO_TAG" ADD CONSTRAINT "SYS_C0056666" CHECK ("DATA_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "DATABLAU_NACOS"."CONFIG_INFO_TAG" ADD CONSTRAINT "SYS_C0056667" CHECK ("CONTENT" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "DATABLAU_NACOS"."CONFIG_INFO_TAG" ADD CONSTRAINT "SYS_C0056668" CHECK ("GMT_CREATE" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "DATABLAU_NACOS"."CONFIG_INFO_TAG" ADD CONSTRAINT "SYS_C0056669" CHECK ("GMT_MODIFIED" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "DATABLAU_NACOS"."CONFIG_INFO_TAG" ADD CONSTRAINT "SYS_C0056670" CHECK ("GROUP_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- INDEXES STRUCTURE FOR TABLE CONFIG_INFO_TAG
-- ----------------------------
CREATE UNIQUE INDEX "DATABLAU_NACOS"."UK_CONFIG_INFO_TAG"
    ON "DATABLAU_NACOS"."CONFIG_INFO_TAG" ("DATA_ID" ASC, "GROUP_ID" ASC, "TENANT_ID" ASC, "TAG_ID" ASC)
    LOGGING
  VISIBLE
PCTFREE 10
INITRANS 2
STORAGE (
  INITIAL 65536
  NEXT 1048576
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
  FLASH_CACHE DEFAULT
)
   USABLE;

-- ----------------------------
-- PRIMARY KEY STRUCTURE FOR TABLE CONFIG_TAGS_RELATION
-- ----------------------------
ALTER TABLE "DATABLAU_NACOS"."CONFIG_TAGS_RELATION" ADD CONSTRAINT "SYS_C0056695" PRIMARY KEY ("NID");

-- ----------------------------
-- CHECKS STRUCTURE FOR TABLE CONFIG_TAGS_RELATION
-- ----------------------------
ALTER TABLE "DATABLAU_NACOS"."CONFIG_TAGS_RELATION" ADD CONSTRAINT "SYS_C0056672" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "DATABLAU_NACOS"."CONFIG_TAGS_RELATION" ADD CONSTRAINT "SYS_C0056673" CHECK ("DATA_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "DATABLAU_NACOS"."CONFIG_TAGS_RELATION" ADD CONSTRAINT "SYS_C0056674" CHECK ("GROUP_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "DATABLAU_NACOS"."CONFIG_TAGS_RELATION" ADD CONSTRAINT "SYS_C0056678" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "DATABLAU_NACOS"."CONFIG_TAGS_RELATION" ADD CONSTRAINT "SYS_C0056679" CHECK ("DATA_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "DATABLAU_NACOS"."CONFIG_TAGS_RELATION" ADD CONSTRAINT "SYS_C0056680" CHECK ("GROUP_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "DATABLAU_NACOS"."CONFIG_TAGS_RELATION" ADD CONSTRAINT "SYS_C0056684" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "DATABLAU_NACOS"."CONFIG_TAGS_RELATION" ADD CONSTRAINT "SYS_C0056685" CHECK ("DATA_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "DATABLAU_NACOS"."CONFIG_TAGS_RELATION" ADD CONSTRAINT "SYS_C0056689" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "DATABLAU_NACOS"."CONFIG_TAGS_RELATION" ADD CONSTRAINT "SYS_C0056690" CHECK ("DATA_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "DATABLAU_NACOS"."CONFIG_TAGS_RELATION" ADD CONSTRAINT "SYS_C0056694" CHECK ("GROUP_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "DATABLAU_NACOS"."CONFIG_TAGS_RELATION" ADD CONSTRAINT "SYS_C0056696" CHECK ("TAG_NAME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "DATABLAU_NACOS"."CONFIG_TAGS_RELATION" ADD CONSTRAINT "SYS_C0056697" CHECK ("NID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- INDEXES STRUCTURE FOR TABLE CONFIG_TAGS_RELATION
-- ----------------------------
CREATE UNIQUE INDEX "DATABLAU_NACOS"."UK_CONFIG_TAGS_RELATION"
    ON "DATABLAU_NACOS"."CONFIG_TAGS_RELATION" ("ID" ASC, "TAG_NAME" ASC, "TAG_TYPE" ASC)
    LOGGING
  VISIBLE
PCTFREE 10
INITRANS 2
STORAGE (
  INITIAL 65536
  NEXT 1048576
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
  FLASH_CACHE DEFAULT
)
   USABLE;

-- ----------------------------
-- PRIMARY KEY STRUCTURE FOR TABLE GROUP_CAPACITY
-- ----------------------------
ALTER TABLE "DATABLAU_NACOS"."GROUP_CAPACITY" ADD CONSTRAINT "SYS_C0056544" PRIMARY KEY ("ID");

-- ----------------------------
-- CHECKS STRUCTURE FOR TABLE GROUP_CAPACITY
-- ----------------------------
ALTER TABLE "DATABLAU_NACOS"."GROUP_CAPACITY" ADD CONSTRAINT "SYS_C0056534" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "DATABLAU_NACOS"."GROUP_CAPACITY" ADD CONSTRAINT "SYS_C0056535" CHECK ("GROUP_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "DATABLAU_NACOS"."GROUP_CAPACITY" ADD CONSTRAINT "SYS_C0056536" CHECK ("QUOTA" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "DATABLAU_NACOS"."GROUP_CAPACITY" ADD CONSTRAINT "SYS_C0056537" CHECK ("USAGE" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "DATABLAU_NACOS"."GROUP_CAPACITY" ADD CONSTRAINT "SYS_C0056538" CHECK ("MAX_SIZE" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "DATABLAU_NACOS"."GROUP_CAPACITY" ADD CONSTRAINT "SYS_C0056539" CHECK ("MAX_AGGR_COUNT" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "DATABLAU_NACOS"."GROUP_CAPACITY" ADD CONSTRAINT "SYS_C0056540" CHECK ("MAX_AGGR_SIZE" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "DATABLAU_NACOS"."GROUP_CAPACITY" ADD CONSTRAINT "SYS_C0056541" CHECK ("MAX_HISTORY_COUNT" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "DATABLAU_NACOS"."GROUP_CAPACITY" ADD CONSTRAINT "SYS_C0056542" CHECK ("GMT_CREATE" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "DATABLAU_NACOS"."GROUP_CAPACITY" ADD CONSTRAINT "SYS_C0056543" CHECK ("GMT_MODIFIED" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- INDEXES STRUCTURE FOR TABLE GROUP_CAPACITY
-- ----------------------------
CREATE UNIQUE INDEX "DATABLAU_NACOS"."UK_GROUP_ID"
    ON "DATABLAU_NACOS"."GROUP_CAPACITY" ("GROUP_ID" ASC)
    LOGGING
  VISIBLE
PCTFREE 10
INITRANS 2
STORAGE (
  INITIAL 65536
  NEXT 1048576
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
  FLASH_CACHE DEFAULT
)
   USABLE;

-- ----------------------------
-- PRIMARY KEY STRUCTURE FOR TABLE HIS_CONFIG_INFO
-- ----------------------------
ALTER TABLE "DATABLAU_NACOS"."HIS_CONFIG_INFO" ADD CONSTRAINT "SYS_C0056722" PRIMARY KEY ("NID");

-- ----------------------------
-- CHECKS STRUCTURE FOR TABLE HIS_CONFIG_INFO
-- ----------------------------
ALTER TABLE "DATABLAU_NACOS"."HIS_CONFIG_INFO" ADD CONSTRAINT "SYS_C0056699" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "DATABLAU_NACOS"."HIS_CONFIG_INFO" ADD CONSTRAINT "SYS_C0056700" CHECK ("DATA_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "DATABLAU_NACOS"."HIS_CONFIG_INFO" ADD CONSTRAINT "SYS_C0056701" CHECK ("GROUP_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "DATABLAU_NACOS"."HIS_CONFIG_INFO" ADD CONSTRAINT "SYS_C0056702" CHECK ("CONTENT" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "DATABLAU_NACOS"."HIS_CONFIG_INFO" ADD CONSTRAINT "SYS_C0056703" CHECK ("GMT_CREATE" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "DATABLAU_NACOS"."HIS_CONFIG_INFO" ADD CONSTRAINT "SYS_C0056704" CHECK ("GMT_MODIFIED" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "DATABLAU_NACOS"."HIS_CONFIG_INFO" ADD CONSTRAINT "SYS_C0056705" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "DATABLAU_NACOS"."HIS_CONFIG_INFO" ADD CONSTRAINT "SYS_C0056706" CHECK ("DATA_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "DATABLAU_NACOS"."HIS_CONFIG_INFO" ADD CONSTRAINT "SYS_C0056707" CHECK ("GROUP_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "DATABLAU_NACOS"."HIS_CONFIG_INFO" ADD CONSTRAINT "SYS_C0056708" CHECK ("CONTENT" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "DATABLAU_NACOS"."HIS_CONFIG_INFO" ADD CONSTRAINT "SYS_C0056709" CHECK ("GMT_CREATE" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "DATABLAU_NACOS"."HIS_CONFIG_INFO" ADD CONSTRAINT "SYS_C0056710" CHECK ("GMT_MODIFIED" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "DATABLAU_NACOS"."HIS_CONFIG_INFO" ADD CONSTRAINT "SYS_C0056711" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "DATABLAU_NACOS"."HIS_CONFIG_INFO" ADD CONSTRAINT "SYS_C0056712" CHECK ("DATA_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "DATABLAU_NACOS"."HIS_CONFIG_INFO" ADD CONSTRAINT "SYS_C0056713" CHECK ("CONTENT" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "DATABLAU_NACOS"."HIS_CONFIG_INFO" ADD CONSTRAINT "SYS_C0056714" CHECK ("GMT_CREATE" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "DATABLAU_NACOS"."HIS_CONFIG_INFO" ADD CONSTRAINT "SYS_C0056715" CHECK ("GMT_MODIFIED" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "DATABLAU_NACOS"."HIS_CONFIG_INFO" ADD CONSTRAINT "SYS_C0056716" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "DATABLAU_NACOS"."HIS_CONFIG_INFO" ADD CONSTRAINT "SYS_C0056717" CHECK ("DATA_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "DATABLAU_NACOS"."HIS_CONFIG_INFO" ADD CONSTRAINT "SYS_C0056718" CHECK ("CONTENT" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "DATABLAU_NACOS"."HIS_CONFIG_INFO" ADD CONSTRAINT "SYS_C0056719" CHECK ("GMT_CREATE" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "DATABLAU_NACOS"."HIS_CONFIG_INFO" ADD CONSTRAINT "SYS_C0056720" CHECK ("GMT_MODIFIED" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "DATABLAU_NACOS"."HIS_CONFIG_INFO" ADD CONSTRAINT "SYS_C0056721" CHECK ("GROUP_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "DATABLAU_NACOS"."HIS_CONFIG_INFO" ADD CONSTRAINT "SYS_C0056723" CHECK ("NID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- INDEXES STRUCTURE FOR TABLE HIS_CONFIG_INFO
-- ----------------------------
CREATE INDEX "DATABLAU_NACOS"."IDX_DID"
    ON "DATABLAU_NACOS"."HIS_CONFIG_INFO" ("DATA_ID" ASC)
    LOGGING
  VISIBLE
PCTFREE 10
INITRANS 2
STORAGE (
  INITIAL 65536
  NEXT 1048576
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
  FLASH_CACHE DEFAULT
)
   USABLE;
CREATE INDEX "DATABLAU_NACOS"."IDX_GMT_CREATE"
    ON "DATABLAU_NACOS"."HIS_CONFIG_INFO" ("GMT_CREATE" ASC)
    LOGGING
  VISIBLE
PCTFREE 10
INITRANS 2
STORAGE (
  INITIAL 65536
  NEXT 1048576
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
  FLASH_CACHE DEFAULT
)
   USABLE;
CREATE INDEX "DATABLAU_NACOS"."IDX_GMT_MODIFIED"
    ON "DATABLAU_NACOS"."HIS_CONFIG_INFO" ("GMT_MODIFIED" ASC)
    LOGGING
  VISIBLE
PCTFREE 10
INITRANS 2
STORAGE (
  INITIAL 65536
  NEXT 1048576
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
  FLASH_CACHE DEFAULT
)
   USABLE;

-- ----------------------------
-- PRIMARY KEY STRUCTURE FOR TABLE PERMISSIONS
-- ----------------------------
--ALTER TABLE "DATABLAU_NACOS"."PERMISSIONS" ADD CONSTRAINT "SYS_C0056738" PRIMARY KEY ("ID");

-- ----------------------------
-- CHECKS STRUCTURE FOR TABLE PERMISSIONS
-- ----------------------------
--ALTER TABLE "DATABLAU_NACOS"."PERMISSIONS" ADD CONSTRAINT "SYS_C0056737" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- PRIMARY KEY STRUCTURE FOR TABLE ROLES
-- ----------------------------
--ALTER TABLE "DATABLAU_NACOS"."ROLES" ADD CONSTRAINT "SYS_C0056736" PRIMARY KEY ("ID");

-- ----------------------------
-- CHECKS STRUCTURE FOR TABLE ROLES
-- ----------------------------
--ALTER TABLE "DATABLAU_NACOS"."ROLES" ADD CONSTRAINT "SYS_C0056733" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "DATABLAU_NACOS"."ROLES" ADD CONSTRAINT "SYS_C0056734" CHECK ("USERNAME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "DATABLAU_NACOS"."ROLES" ADD CONSTRAINT "SYS_C0056735" CHECK ("ROLE" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- PRIMARY KEY STRUCTURE FOR TABLE TENANT_CAPACITY
-- ----------------------------
ALTER TABLE "DATABLAU_NACOS"."TENANT_CAPACITY" ADD CONSTRAINT "SYS_C0056598" PRIMARY KEY ("ID");

-- ----------------------------
-- CHECKS STRUCTURE FOR TABLE TENANT_CAPACITY
-- ----------------------------
ALTER TABLE "DATABLAU_NACOS"."TENANT_CAPACITY" ADD CONSTRAINT "SYS_C0056578" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "DATABLAU_NACOS"."TENANT_CAPACITY" ADD CONSTRAINT "SYS_C0056579" CHECK ("TENANT_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "DATABLAU_NACOS"."TENANT_CAPACITY" ADD CONSTRAINT "SYS_C0056580" CHECK ("QUOTA" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "DATABLAU_NACOS"."TENANT_CAPACITY" ADD CONSTRAINT "SYS_C0056581" CHECK ("USAGE" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "DATABLAU_NACOS"."TENANT_CAPACITY" ADD CONSTRAINT "SYS_C0056582" CHECK ("MAX_SIZE" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "DATABLAU_NACOS"."TENANT_CAPACITY" ADD CONSTRAINT "SYS_C0056583" CHECK ("MAX_AGGR_COUNT" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "DATABLAU_NACOS"."TENANT_CAPACITY" ADD CONSTRAINT "SYS_C0056584" CHECK ("MAX_AGGR_SIZE" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "DATABLAU_NACOS"."TENANT_CAPACITY" ADD CONSTRAINT "SYS_C0056585" CHECK ("MAX_HISTORY_COUNT" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "DATABLAU_NACOS"."TENANT_CAPACITY" ADD CONSTRAINT "SYS_C0056586" CHECK ("GMT_CREATE" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "DATABLAU_NACOS"."TENANT_CAPACITY" ADD CONSTRAINT "SYS_C0056587" CHECK ("GMT_MODIFIED" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "DATABLAU_NACOS"."TENANT_CAPACITY" ADD CONSTRAINT "SYS_C0056588" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "DATABLAU_NACOS"."TENANT_CAPACITY" ADD CONSTRAINT "SYS_C0056589" CHECK ("TENANT_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "DATABLAU_NACOS"."TENANT_CAPACITY" ADD CONSTRAINT "SYS_C0056590" CHECK ("QUOTA" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "DATABLAU_NACOS"."TENANT_CAPACITY" ADD CONSTRAINT "SYS_C0056591" CHECK ("USAGE" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "DATABLAU_NACOS"."TENANT_CAPACITY" ADD CONSTRAINT "SYS_C0056592" CHECK ("MAX_SIZE" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "DATABLAU_NACOS"."TENANT_CAPACITY" ADD CONSTRAINT "SYS_C0056593" CHECK ("MAX_AGGR_COUNT" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "DATABLAU_NACOS"."TENANT_CAPACITY" ADD CONSTRAINT "SYS_C0056594" CHECK ("MAX_AGGR_SIZE" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "DATABLAU_NACOS"."TENANT_CAPACITY" ADD CONSTRAINT "SYS_C0056595" CHECK ("MAX_HISTORY_COUNT" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "DATABLAU_NACOS"."TENANT_CAPACITY" ADD CONSTRAINT "SYS_C0056596" CHECK ("GMT_CREATE" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "DATABLAU_NACOS"."TENANT_CAPACITY" ADD CONSTRAINT "SYS_C0056597" CHECK ("GMT_MODIFIED" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- INDEXES STRUCTURE FOR TABLE ROLES
-- ----------------------------
CREATE UNIQUE INDEX "DATABLAU_NACOS"."UK_ROLES"
    ON "DATABLAU_NACOS"."ROLES" ("USERNAME" ASC,"ROLE" ASC )
    LOGGING
  VISIBLE
PCTFREE 10
INITRANS 2
STORAGE (
  INITIAL 65536
  NEXT 1048576
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
  FLASH_CACHE DEFAULT
)
   USABLE;
-- ----------------------------
-- INDEXES STRUCTURE FOR TABLE TENANT_CAPACITY
-- ----------------------------
CREATE UNIQUE INDEX "DATABLAU_NACOS"."UK_TENANT_ID"
    ON "DATABLAU_NACOS"."TENANT_CAPACITY" ("TENANT_ID" ASC)
    LOGGING
  VISIBLE
PCTFREE 10
INITRANS 2
STORAGE (
  INITIAL 65536
  NEXT 1048576
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
  FLASH_CACHE DEFAULT
)
   USABLE;
-- ----------------------------
-- INDEXES STRUCTURE FOR TABLE permissions
-- ----------------------------
CREATE UNIQUE INDEX "DATABLAU_NACOS"."UK_PERMISSIONS"
    ON "DATABLAU_NACOS"."PERMISSIONS" ("ROLE" ASC,"RESOURCE" ASC,"ACTION" ASC)
    LOGGING
  VISIBLE
PCTFREE 10
INITRANS 2
STORAGE (
  INITIAL 65536
  NEXT 1048576
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
  FLASH_CACHE DEFAULT
)
   USABLE;

-- ----------------------------
-- PRIMARY KEY STRUCTURE FOR TABLE TENANT_INFO
-- ----------------------------
ALTER TABLE "DATABLAU_NACOS"."TENANT_INFO" ADD CONSTRAINT "SYS_C0056727" PRIMARY KEY ("ID");

-- ----------------------------
-- CHECKS STRUCTURE FOR TABLE TENANT_INFO
-- ----------------------------
ALTER TABLE "DATABLAU_NACOS"."TENANT_INFO" ADD CONSTRAINT "SYS_C0056725" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "DATABLAU_NACOS"."TENANT_INFO" ADD CONSTRAINT "SYS_C0056726" CHECK ("KP" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- INDEXES STRUCTURE FOR TABLE TENANT_INFO
-- ----------------------------
CREATE INDEX "DATABLAU_NACOS"."IDX_TENANT_ID"
    ON "DATABLAU_NACOS"."TENANT_INFO" ("TENANT_ID" ASC)
    LOGGING
  VISIBLE
PCTFREE 10
INITRANS 2
STORAGE (
  INITIAL 65536
  NEXT 1048576
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
  FLASH_CACHE DEFAULT
)
   USABLE;
CREATE UNIQUE INDEX "DATABLAU_NACOS"."UK_TENANT_INFO"
    ON "DATABLAU_NACOS"."TENANT_INFO" ("KP" ASC, "TENANT_ID" ASC)
    LOGGING
  VISIBLE
PCTFREE 10
INITRANS 2
STORAGE (
  INITIAL 65536
  NEXT 1048576
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
  FLASH_CACHE DEFAULT
)
   USABLE;

-- ----------------------------
-- PRIMARY KEY STRUCTURE FOR TABLE USERS
-- ----------------------------
ALTER TABLE "DATABLAU_NACOS"."USERS" ADD CONSTRAINT "SYS_C0056732" PRIMARY KEY ("USERNAME");

-- ----------------------------
-- CHECKS STRUCTURE FOR TABLE USERS
-- ----------------------------
--ALTER TABLE "DATABLAU_NACOS"."USERS" ADD CONSTRAINT "SYS_C0056728" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "DATABLAU_NACOS"."USERS" ADD CONSTRAINT "SYS_C0056729" CHECK ("USERNAME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "DATABLAU_NACOS"."USERS" ADD CONSTRAINT "SYS_C0056730" CHECK ("PASSWORD" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "DATABLAU_NACOS"."USERS" ADD CONSTRAINT "SYS_C0056731" CHECK ("ENABLED" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
