/*
 * Copyright 1999-2018 Alibaba Group Holding Ltd.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


CREATE TABLE "CONFIG_INFO" (
                               "ID" NUMBER(20,0)  NOT NULL,
                               "DATA_ID" NVARCHAR2(255)  NOT NULL,
                               "GROUP_ID" NVARCHAR2(255) DEFAULT NULL,
                               "CONTENT" NCLOB  NOT NULL,
                               "MD5" NVARCHAR2(32) DEFAULT NULL,
                               "GMT_CREATE" DATE  ,
                               "GMT_MODIFIED" DATE ,
                               "SRC_USER" NCLOB DEFAULT NULL,
                               "SRC_IP" NVARCHAR2(50) DEFAULT NULL,
                               "APP_NAME" NVARCHAR2(128) DEFAULT NULL,
                               "TENANT_ID" NVARCHAR2(128)  DEFAULT '',
                               "C_DESC" NVARCHAR2(256) DEFAULT NULL,
                               "C_USE" NVARCHAR2(64) DEFAULT NULL,
                               "EFFECT" NVARCHAR2(64) DEFAULT NULL,
                               "TYPE" NVARCHAR2(64) DEFAULT NULL,
                               "C_SCHEMA" NCLOB ,
                               "ENCRYPTED_DATA_KEY" NVARCHAR2(1024) DEFAULT '')

    LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536
  NEXT 1048576
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;
COMMENT ON COLUMN "CONFIG_INFO"."ID" IS 'ID';
COMMENT ON COLUMN "CONFIG_INFO"."DATA_ID" IS 'DATA_ID';
COMMENT ON COLUMN "CONFIG_INFO"."GROUP_ID" IS 'GROUP_ID';
COMMENT ON COLUMN "CONFIG_INFO"."CONTENT" IS 'CONTENT';
COMMENT ON COLUMN "CONFIG_INFO"."MD5" IS 'MD5';
COMMENT ON COLUMN "CONFIG_INFO"."GMT_CREATE" IS '创建时间';
COMMENT ON COLUMN "CONFIG_INFO"."GMT_MODIFIED" IS '修改时间';
COMMENT ON COLUMN "CONFIG_INFO"."SRC_USER" IS 'SOURCE USER';
COMMENT ON COLUMN "CONFIG_INFO"."SRC_IP" IS 'SOURCE IP';
COMMENT ON COLUMN "CONFIG_INFO"."APP_NAME" IS 'APP_NAME';
COMMENT ON COLUMN "CONFIG_INFO"."TENANT_ID" IS '租户字段';
COMMENT ON COLUMN "CONFIG_INFO"."C_DESC" IS 'CONFIGURATION DESCRIPTION';
COMMENT ON COLUMN "CONFIG_INFO"."C_USE" IS 'CONFIGURATION USAGE';
COMMENT ON COLUMN "CONFIG_INFO"."EFFECT" IS '配置生效的描述';
COMMENT ON COLUMN "CONFIG_INFO"."TYPE" IS '配置的类型';
COMMENT ON COLUMN "CONFIG_INFO"."C_SCHEMA" IS '配置的模式';
COMMENT ON COLUMN "CONFIG_INFO"."ENCRYPTED_DATA_KEY" IS '密钥';
COMMENT ON TABLE "CONFIG_INFO" IS 'config_info';
CREATE SEQUENCE config_info_info_id_seq
    START WITH 1
    INCREMENT BY 1
    MINVALUE 1
    MAXVALUE 999999999999999999
    CACHE 20;

create or replace trigger config_info_id
          before insert
          on CONFIG_INFO
          for each row
begin
select config_info_info_id_seq.nextval into:new.ID from dual;
end config_info_id;

-- ALTER TABLE CONFIG_INFO
--     MODIFY ID DEFAULT config_info_info_id_seq.NEXTVAL;

-- ----------------------------
-- Table structure for CONFIG_INFO_AGGR
-- ----------------------------
CREATE TABLE "CONFIG_INFO_AGGR" (
                                    "ID" NUMBER(20,0)  NOT NULL,
                                    "DATA_ID" NVARCHAR2(255)  NOT NULL,
                                    "GROUP_ID" NVARCHAR2(255)  NOT NULL,
                                    "DATUM_ID" NVARCHAR2(255)  NOT NULL,
                                    "CONTENT" NCLOB  NOT NULL,
                                    "GMT_MODIFIED" DATE  NOT NULL,
                                    "APP_NAME" NVARCHAR2(128) DEFAULT NULL,
                                    "TENANT_ID" NVARCHAR2(128) DEFAULT ''
)
    LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536
  NEXT 1048576
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;
COMMENT ON COLUMN "CONFIG_INFO_AGGR"."ID" IS 'id';
COMMENT ON COLUMN "CONFIG_INFO_AGGR"."DATA_ID" IS 'data_id';
COMMENT ON COLUMN "CONFIG_INFO_AGGR"."GROUP_ID" IS 'group_id';
COMMENT ON COLUMN "CONFIG_INFO_AGGR"."DATUM_ID" IS 'datum_id';
COMMENT ON COLUMN "CONFIG_INFO_AGGR"."CONTENT" IS '内容';
COMMENT ON COLUMN "CONFIG_INFO_AGGR"."GMT_MODIFIED" IS '修改时间';
COMMENT ON COLUMN "CONFIG_INFO_AGGR"."TENANT_ID" IS '租户字段';
COMMENT ON TABLE "CONFIG_INFO_AGGR" IS '增加租户字段';
COMMENT ON COLUMN "CONFIG_INFO_AGGR"."ID" IS 'ID';
COMMENT ON COLUMN "CONFIG_INFO_AGGR"."DATA_ID" IS 'DATA_ID';
COMMENT ON COLUMN "CONFIG_INFO_AGGR"."GROUP_ID" IS 'GROUP_ID';
COMMENT ON COLUMN "CONFIG_INFO_AGGR"."CONTENT" IS '内容';
COMMENT ON COLUMN "CONFIG_INFO_AGGR"."GMT_MODIFIED" IS '修改时间';
COMMENT ON COLUMN "CONFIG_INFO_AGGR"."APP_NAME" IS 'APP_NAME';
COMMENT ON COLUMN "CONFIG_INFO_AGGR"."TENANT_ID" IS '租户字段';
COMMENT ON COLUMN "CONFIG_INFO_AGGR"."DATUM_ID" IS 'DATUM_ID';
CREATE SEQUENCE config_info_aggr_id_seq
    START WITH 1
    INCREMENT BY 1
    MINVALUE 1
    MAXVALUE 999999999999999999
    CACHE 20;

-- ALTER TABLE CONFIG_INFO_AGGR
--     MODIFY ID DEFAULT config_info_aggr_id_seq.NEXTVAL;
create or replace trigger CONFIG_INFO_AGGR_id
          before insert
          on CONFIG_INFO_AGGR
          for each row
begin
select config_info_aggr_id_seq.nextval into:new.ID from dual;
end CONFIG_INFO_AGGR_id;

-- ----------------------------
-- Table structure for CONFIG_INFO_BETA
-- ----------------------------
CREATE TABLE "CONFIG_INFO_BETA" (
                                    "ID" NUMBER(20,0)  NOT NULL,
                                    "DATA_ID" NVARCHAR2(255)  NOT NULL,
                                    "GROUP_ID" NVARCHAR2(128)  NOT NULL,
                                    "APP_NAME" NVARCHAR2(128) DEFAULT NULL,
                                    "CONTENT" NCLOB  NOT NULL,
                                    "BETA_IPS" NCLOB DEFAULT NULL,
                                    "MD5" NVARCHAR2(32) DEFAULT NULL,
                                    "GMT_CREATE" DATE  NOT NULL,
                                    "GMT_MODIFIED" DATE  NOT NULL,
                                    "SRC_USER" NCLOB DEFAULT NULL,
                                    "SRC_IP" NVARCHAR2(50)DEFAULT NULL ,
                                    "TENANT_ID" NVARCHAR2(128) DEFAULT '',
                                    "ENCRYPTED_DATA_KEY" NVARCHAR2(1024)  DEFAULT ''
)
    LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536
  NEXT 1048576
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;
COMMENT ON COLUMN "CONFIG_INFO_BETA"."ID" IS 'ID';
COMMENT ON COLUMN "CONFIG_INFO_BETA"."DATA_ID" IS 'DATA_ID';
COMMENT ON COLUMN "CONFIG_INFO_BETA"."GROUP_ID" IS 'GROUP_ID';
COMMENT ON COLUMN "CONFIG_INFO_BETA"."CONTENT" IS 'CONTENT';
COMMENT ON COLUMN "CONFIG_INFO_BETA"."MD5" IS 'MD5';
COMMENT ON COLUMN "CONFIG_INFO_BETA"."GMT_CREATE" IS '创建时间';
COMMENT ON COLUMN "CONFIG_INFO_BETA"."GMT_MODIFIED" IS '修改时间';
COMMENT ON COLUMN "CONFIG_INFO_BETA"."SRC_USER" IS 'SOURCE USER';
COMMENT ON COLUMN "CONFIG_INFO_BETA"."SRC_IP" IS 'SOURCE IP';
COMMENT ON COLUMN "CONFIG_INFO_BETA"."APP_NAME" IS 'APP_NAME';
COMMENT ON COLUMN "CONFIG_INFO_BETA"."TENANT_ID" IS '租户字段';
COMMENT ON COLUMN "CONFIG_INFO_BETA"."ENCRYPTED_DATA_KEY" IS '密钥';
COMMENT ON COLUMN "CONFIG_INFO_BETA"."BETA_IPS" IS 'BETA_IPS';
COMMENT ON TABLE "CONFIG_INFO_BETA" IS 'config_info_beta';
CREATE SEQUENCE config_info_beta_id_seq
    START WITH 1
    INCREMENT BY 1
    MINVALUE 1
    MAXVALUE 999999999999999999
    CACHE 20;

-- ALTER TABLE CONFIG_INFO_BETA
--     MODIFY ID DEFAULT config_info_beta_id_seq.NEXTVAL;
create or replace trigger config_info_beta_id
          before insert
          on CONFIG_INFO_BETA
          for each row
begin
select config_info_beta_id_seq.nextval into:new.ID from dual;
end config_info_beta_id;
-- ----------------------------
-- Table structure for CONFIG_INFO_TAG
-- ----------------------------
CREATE TABLE "CONFIG_INFO_TAG" (
                                   "ID" NUMBER(20,0)  NOT NULL,
                                   "DATA_ID" NVARCHAR2(255)  NOT NULL,
                                   "GROUP_ID" NVARCHAR2(128)  NOT NULL,
                                   "CONTENT" NCLOB  DEFAULT NULL,
                                   "MD5" NVARCHAR2(32) DEFAULT NULL,
                                   "GMT_CREATE" DATE ,
                                   "GMT_MODIFIED" DATE ,
                                   "SRC_USER" NCLOB DEFAULT NULL,
                                   "SRC_IP" NVARCHAR2(50)DEFAULT NULL,
                                   "APP_NAME" NVARCHAR2(128) DEFAULT NULL,
                                   "TENANT_ID" NVARCHAR2(128)  DEFAULT '',
                                   "TAG_ID" NVARCHAR2(128)
)
    LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536
  NEXT 1048576
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;
COMMENT ON COLUMN "CONFIG_INFO_TAG"."ID" IS 'ID';
COMMENT ON COLUMN "CONFIG_INFO_TAG"."DATA_ID" IS 'DATA_ID';
COMMENT ON COLUMN "CONFIG_INFO_TAG"."GROUP_ID" IS 'GROUP_ID';
COMMENT ON COLUMN "CONFIG_INFO_TAG"."CONTENT" IS 'CONTENT';
COMMENT ON COLUMN "CONFIG_INFO_TAG"."MD5" IS 'MD5';
COMMENT ON COLUMN "CONFIG_INFO_TAG"."GMT_CREATE" IS '创建时间';
COMMENT ON COLUMN "CONFIG_INFO_TAG"."GMT_MODIFIED" IS '修改时间';
COMMENT ON COLUMN "CONFIG_INFO_TAG"."SRC_USER" IS 'SOURCE USER';
COMMENT ON COLUMN "CONFIG_INFO_TAG"."SRC_IP" IS 'SOURCE IP';
COMMENT ON COLUMN "CONFIG_INFO_TAG"."APP_NAME" IS 'APP_NAME';
COMMENT ON COLUMN "CONFIG_INFO_TAG"."TENANT_ID" IS '租户字段';
COMMENT ON COLUMN "CONFIG_INFO_TAG"."TAG_ID" IS 'TAG_ID';
COMMENT ON TABLE "CONFIG_INFO_TAG" IS 'config_info_tag';
CREATE SEQUENCE config_info_tag_id_seq
    START WITH 1
    INCREMENT BY 1
    MINVALUE 1
    MAXVALUE 999999999999999999
    CACHE 20;

-- ALTER TABLE CONFIG_INFO_TAG
--     MODIFY ID DEFAULT config_info_tag_id_seq.NEXTVAL;

create or replace trigger config_info_tag_id
          before insert
          on CONFIG_INFO_TAG
          for each row
begin
select config_info_tag_id_seq.nextval into:new.ID from dual;
end config_info_tag_id;
-- ----------------------------
-- Table structure for CONFIG_TAGS_RELATION
-- ----------------------------
CREATE TABLE "CONFIG_TAGS_RELATION" (
                                        "ID" NUMBER(20,0)  NOT NULL,
                                        "DATA_ID" NVARCHAR2(255)  NOT NULL,
                                        "GROUP_ID" NVARCHAR2(128)  NOT NULL,
                                        "TENANT_ID" NVARCHAR2(128) DEFAULT '',
                                        "TAG_NAME" NVARCHAR2(128)  NOT NULL,
                                        "TAG_TYPE" NVARCHAR2(64) DEFAULT NULL,
                                        "NID" NUMBER(20,0)  NOT NULL
)
    LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536
  NEXT 1048576
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;
COMMENT ON COLUMN "CONFIG_TAGS_RELATION"."ID" IS 'ID';
COMMENT ON COLUMN "CONFIG_TAGS_RELATION"."DATA_ID" IS 'DATA_ID';
COMMENT ON COLUMN "CONFIG_TAGS_RELATION"."GROUP_ID" IS 'GROUP_ID';
COMMENT ON COLUMN "CONFIG_TAGS_RELATION"."TENANT_ID" IS '租户字段';
COMMENT ON COLUMN "CONFIG_TAGS_RELATION"."TAG_NAME" IS 'TAG_NAME';
COMMENT ON COLUMN "CONFIG_TAGS_RELATION"."TAG_TYPE" IS 'TAG_TYPE';
COMMENT ON COLUMN "CONFIG_TAGS_RELATION"."NID" IS 'NID, 自增长标识NID';
COMMENT ON TABLE "CONFIG_TAGS_RELATION" IS 'config_tag_relation';
CREATE SEQUENCE config_tags_relation_id_seq
    START WITH 1
    INCREMENT BY 1
    MINVALUE 1
    MAXVALUE 999999999999999999
    CACHE 20;
--
-- ALTER TABLE CONFIG_TAGS_RELATION
--     MODIFY ID DEFAULT config_tags_relation_id_seq.NEXTVAL;

create or replace trigger config_tags_relation_id
          before insert
          on CONFIG_TAGS_RELATION
          for each row
begin
select config_tags_relation_id_seq.nextval into:new.ID from dual;
end config_tags_relation_id;
-- ----------------------------
-- Table structure for GROUP_CAPACITY
-- ----------------------------
CREATE TABLE "GROUP_CAPACITY" (
                                  "ID" NUMBER(20,0)  NOT NULL,
                                  "GROUP_ID" NVARCHAR2(128) DEFAULT '' NOT NULL,
                                  "QUOTA" NUMBER(11,0) DEFAULT 0 NOT NULL,
                                  "USAGE" NUMBER(11,0) DEFAULT 0 NOT NULL,
                                  "MAX_SIZE" NUMBER(11,0) DEFAULT 0 NOT NULL,
                                  "MAX_AGGR_COUNT" NUMBER(11,0) DEFAULT 0 NOT NULL,
                                  "MAX_AGGR_SIZE" NUMBER(11,0)  DEFAULT 0 NOT NULL,
                                  "MAX_HISTORY_COUNT" NUMBER(11,0) DEFAULT 0 NOT NULL,
                                  "GMT_CREATE" DATE  ,
                                  "GMT_MODIFIED" DATE
)
    LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536
  NEXT 1048576
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;
COMMENT ON COLUMN "GROUP_CAPACITY"."ID" IS '主键ID';
COMMENT ON COLUMN "GROUP_CAPACITY"."GROUP_ID" IS 'Group ID，空字符表示整个集群';
COMMENT ON COLUMN "GROUP_CAPACITY"."QUOTA" IS '配额，0表示使用默认值';
COMMENT ON COLUMN "GROUP_CAPACITY"."USAGE" IS '使用量';
COMMENT ON COLUMN "GROUP_CAPACITY"."MAX_SIZE" IS '单个配置大小上限，单位为字节，0表示使用默认值';
COMMENT ON COLUMN "GROUP_CAPACITY"."MAX_AGGR_COUNT" IS '聚合子配置最大个数，，0表示使用默认值';
COMMENT ON COLUMN "GROUP_CAPACITY"."MAX_AGGR_SIZE" IS '单个聚合数据的子配置大小上限，单位为字节，0表示使用默认值';
COMMENT ON COLUMN "GROUP_CAPACITY"."MAX_HISTORY_COUNT" IS '最大变更历史数量';
COMMENT ON COLUMN "GROUP_CAPACITY"."GMT_CREATE" IS '创建时间';
COMMENT ON COLUMN "GROUP_CAPACITY"."GMT_MODIFIED" IS '修改时间';
COMMENT ON TABLE "GROUP_CAPACITY" IS '集群、各Group容量信息表';
CREATE SEQUENCE group_capacity_id_seq
    START WITH 1
    INCREMENT BY 1
    MINVALUE 1
    MAXVALUE 999999999999999999
    CACHE 20;

-- ALTER TABLE GROUP_CAPACITY
--     MODIFY ID DEFAULT group_capacity_id_seq.NEXTVAL;

create or replace trigger roup_capacity_id
          before insert
          on GROUP_CAPACITY
          for each row
begin
select group_capacity_id_seq.nextval into:new.ID from dual;
end roup_capacity_id;
-- ----------------------------
-- Table structure for HIS_CONFIG_INFO
-- ----------------------------
CREATE TABLE "HIS_CONFIG_INFO" (
                                   "ID" NUMBER(20,0)  NOT NULL,
                                   "DATA_ID" NVARCHAR2(255)  NOT NULL,
                                   "GROUP_ID" NVARCHAR2(128)  NOT NULL,
                                   "CONTENT" NCLOB  NOT NULL,
                                   "MD5" NVARCHAR2(32) DEFAULT NULL,
                                   "GMT_CREATE" DATE  ,
                                   "GMT_MODIFIED" DATE  ,
                                   "SRC_USER" NCLOB DEFAULT NULL,
                                   "SRC_IP" NVARCHAR2(50) DEFAULT NULL,
                                   "APP_NAME" NVARCHAR2(128) DEFAULT NULL,
                                   "TENANT_ID" NVARCHAR2(128) DEFAULT '',
                                   "NID" NUMBER(20,0)  NOT NULL,
                                   "OP_TYPE" NCHAR(10) ,
                                   "ENCRYPTED_DATA_KEY" NVARCHAR2(1024) DEFAULT ''
)
    LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536
  NEXT 1048576
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;
COMMENT ON COLUMN "HIS_CONFIG_INFO"."ID" IS 'ID';
COMMENT ON COLUMN "HIS_CONFIG_INFO"."DATA_ID" IS 'DATA_ID';
COMMENT ON COLUMN "HIS_CONFIG_INFO"."GROUP_ID" IS 'GROUP_ID';
COMMENT ON COLUMN "HIS_CONFIG_INFO"."CONTENT" IS 'CONTENT';
COMMENT ON COLUMN "HIS_CONFIG_INFO"."MD5" IS 'MD5';
COMMENT ON COLUMN "HIS_CONFIG_INFO"."GMT_CREATE" IS '创建时间';
COMMENT ON COLUMN "HIS_CONFIG_INFO"."GMT_MODIFIED" IS '修改时间';
COMMENT ON COLUMN "HIS_CONFIG_INFO"."SRC_USER" IS 'SOURCE USER';
COMMENT ON COLUMN "HIS_CONFIG_INFO"."SRC_IP" IS 'SOURCE IP';
COMMENT ON COLUMN "HIS_CONFIG_INFO"."APP_NAME" IS 'APP_NAME';
COMMENT ON COLUMN "HIS_CONFIG_INFO"."TENANT_ID" IS '租户字段';
COMMENT ON COLUMN "HIS_CONFIG_INFO"."NID" IS 'NID, 自增标识';
COMMENT ON COLUMN "HIS_CONFIG_INFO"."OP_TYPE" IS 'OPERATION TYPE';
COMMENT ON COLUMN "HIS_CONFIG_INFO"."ENCRYPTED_DATA_KEY" IS '密钥';
CREATE SEQUENCE his_config_info_id_seq
    START WITH 1
    INCREMENT BY 1
    MINVALUE 1
    MAXVALUE 999999999999999999
    CACHE 20;
--
-- ALTER TABLE HIS_CONFIG_INFO
--     MODIFY ID DEFAULT his_config_info_id_seq.NEXTVAL;

create or replace trigger his_config_info_id
          before insert
          on HIS_CONFIG_INFO
          for each row
begin
select his_config_info_id_seq.nextval into:new.ID from dual;
end his_config_info_id;


CREATE SEQUENCE his_config_info_nid_seq
    START WITH 1
    INCREMENT BY 1
    MINVALUE 1
    MAXVALUE 999999999999999999
    CACHE 20;

-- ALTER TABLE HIS_CONFIG_INFO
--     MODIFY NID DEFAULT his_config_info_nid_seq.NEXTVAL;

create or replace trigger his_config_info_nid
          before insert
          on HIS_CONFIG_INFO
          for each row
begin
select his_config_info_nid_seq.nextval into:new.NID from dual;
end his_config_info_nid;

-- ----------------------------
-- Table structure for PERMISSIONS
-- ----------------------------
CREATE TABLE "PERMISSIONS" (
                               "ROLE" NVARCHAR2(50) ,
                               "RESOURCE" NVARCHAR2(255)  ,
                               "ACTION" NVARCHAR2(8)
)
    LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536
  NEXT 1048576
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;



-- ----------------------------
-- Table structure for ROLES
-- ----------------------------
CREATE TABLE "ROLES" (
                         "USERNAME" NVARCHAR2(50)  NOT NULL,
                         "ROLE" NVARCHAR2(50)  NOT NULL
)
    LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536
  NEXT 1048576
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;

-- ----------------------------
-- Table structure for TENANT_CAPACITY
-- ----------------------------
CREATE TABLE "TENANT_CAPACITY" (
                                   "ID" NUMBER(20,0)  NOT NULL,
                                   "TENANT_ID" NVARCHAR2(128) DEFAULT ''  NOT NULL,
                                   "QUOTA" NUMBER(11,0) DEFAULT 0  NOT NULL,
                                   "USAGE" NUMBER(11,0) DEFAULT 0  NOT NULL,
                                   "MAX_SIZE" NUMBER(11,0)  DEFAULT 0 NOT NULL,
                                   "MAX_AGGR_COUNT" NUMBER(11,0) DEFAULT 0   NOT NULL,
                                   "MAX_AGGR_SIZE" NUMBER(11,0) DEFAULT 0  NOT NULL,
                                   "MAX_HISTORY_COUNT" NUMBER(11,0) DEFAULT 0  NOT NULL,
                                   "GMT_CREATE" DATE ,
                                   "GMT_MODIFIED" DATE
)
    LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536
  NEXT 1048576
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;
COMMENT ON COLUMN "TENANT_CAPACITY"."ID" IS '主键ID';
COMMENT ON COLUMN "TENANT_CAPACITY"."TENANT_ID" IS 'Tenant ID';
COMMENT ON COLUMN "TENANT_CAPACITY"."QUOTA" IS '配额，0表示使用默认值';
COMMENT ON COLUMN "TENANT_CAPACITY"."USAGE" IS '使用量';
COMMENT ON COLUMN "TENANT_CAPACITY"."MAX_SIZE" IS '单个配置大小上限，单位为字节，0表示使用默认值';
COMMENT ON COLUMN "TENANT_CAPACITY"."MAX_AGGR_COUNT" IS '聚合子配置最大个数';
COMMENT ON COLUMN "TENANT_CAPACITY"."MAX_AGGR_SIZE" IS '单个聚合数据的子配置大小上限，单位为字节，0表示使用默认值';
COMMENT ON COLUMN "TENANT_CAPACITY"."MAX_HISTORY_COUNT" IS '最大变更历史数量';
COMMENT ON COLUMN "TENANT_CAPACITY"."GMT_CREATE" IS '创建时间';
COMMENT ON COLUMN "TENANT_CAPACITY"."GMT_MODIFIED" IS '修改时间';
COMMENT ON TABLE "TENANT_CAPACITY" IS '租户容量信息表';
CREATE SEQUENCE tenant_capacity_id_seq
    START WITH 1
    INCREMENT BY 1
    MINVALUE 1
    MAXVALUE 999999999999999999
    CACHE 20;

-- ALTER TABLE TENANT_CAPACITY
--     MODIFY ID DEFAULT tenant_capacity_id_seq.NEXTVAL;

create or replace trigger tenant_capacity_id
          before insert
          on TENANT_CAPACITY
          for each row
begin
select tenant_capacity_id_seq.nextval into:new.ID from dual;
end tenant_capacity_id;
-- ----------------------------
-- Table structure for TENANT_INFO
-- ----------------------------
CREATE TABLE "TENANT_INFO" (
                               "ID" NUMBER(20,0)  NOT NULL,
                               "KP" NVARCHAR2(128)  NOT NULL,
                               "TENANT_ID" NVARCHAR2(128) DEFAULT '',
                               "TENANT_NAME" NVARCHAR2(128) DEFAULT '',
                               "TENANT_DESC" NVARCHAR2(256) DEFAULT NULL,
                               "CREATE_SOURCE" NVARCHAR2(32) DEFAULT NULL,
                               "GMT_CREATE" NUMBER(20,0)  ,
                               "GMT_MODIFIED" NUMBER(20,0)
)
    LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536
  NEXT 1048576
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;
COMMENT ON COLUMN "TENANT_INFO"."ID" IS 'id';
COMMENT ON COLUMN "TENANT_INFO"."KP" IS 'kp';
COMMENT ON COLUMN "TENANT_INFO"."TENANT_ID" IS 'tenant_id';
COMMENT ON COLUMN "TENANT_INFO"."TENANT_NAME" IS 'tenant_name';
COMMENT ON COLUMN "TENANT_INFO"."TENANT_DESC" IS 'tenant_desc';
COMMENT ON COLUMN "TENANT_INFO"."CREATE_SOURCE" IS 'create_source';
COMMENT ON COLUMN "TENANT_INFO"."GMT_CREATE" IS '创建时间';
COMMENT ON COLUMN "TENANT_INFO"."GMT_MODIFIED" IS '修改时间';
COMMENT ON TABLE "TENANT_INFO" IS 'tenant_info';

CREATE SEQUENCE tenant_info_id_seq
    START WITH 1
    INCREMENT BY 1
    MINVALUE 1
    MAXVALUE 999999999999999999
    CACHE 20;
--
-- ALTER TABLE TENANT_INFO
--     MODIFY ID DEFAULT tenant_info_id_seq.NEXTVAL;
create or replace trigger tenant_info_id
          before insert
          on TENANT_INFO
          for each row
begin
select tenant_info_id_seq.nextval into:new.ID from dual;
end tenant_info_id;
-- ----------------------------
-- Table structure for USERS
-- ----------------------------
CREATE TABLE "USERS" (
                         "USERNAME" NVARCHAR2(50)  NOT NULL,
                         "PASSWORD" NVARCHAR2(500)  NOT NULL,
                         "ENABLED" NUMBER(4,0)  NOT NULL
)
    LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536
  NEXT 1048576
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;



-- ----------------------------
-- Sequence structure for SEQ_ID
-- ----------------------------
CREATE SEQUENCE "SEQ_ID" MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 NOCACHE;

-- ----------------------------
-- Primary Key structure for table CONFIG_INFO
-- ----------------------------
ALTER TABLE "CONFIG_INFO" ADD CONSTRAINT "SYS_C0012437" PRIMARY KEY ("ID");

-- ----------------------------
-- Checks structure for table CONFIG_INFO
-- ----------------------------
ALTER TABLE "CONFIG_INFO" ADD CONSTRAINT "SYS_C0012370" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "CONFIG_INFO" ADD CONSTRAINT "SYS_C0012371" CHECK ("DATA_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "CONFIG_INFO" ADD CONSTRAINT "SYS_C0012372" CHECK ("CONTENT" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Indexes structure for table CONFIG_INFO
-- ----------------------------
CREATE UNIQUE INDEX "U_G_T"
    ON "CONFIG_INFO" ("DATA_ID" ASC, "GROUP_ID" ASC, "TENANT_ID" ASC)
    LOGGING
PCTFREE 10
INITRANS 2
STORAGE (
  INITIAL 65536
  NEXT 1048576
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
  FLASH_CACHE DEFAULT
);


-- ----------------------------
-- Primary Key structure for table CONFIG_INFO_AGGR
-- ----------------------------
ALTER TABLE "CONFIG_INFO_AGGR" ADD CONSTRAINT "SYS_C0012434" PRIMARY KEY ("ID");

-- ----------------------------
-- Checks structure for table CONFIG_INFO_AGGR
-- ----------------------------
ALTER TABLE "CONFIG_INFO_AGGR" ADD CONSTRAINT "SYS_C0012375" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "CONFIG_INFO_AGGR" ADD CONSTRAINT "SYS_C0012376" CHECK ("DATA_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "CONFIG_INFO_AGGR" ADD CONSTRAINT "SYS_C0012377" CHECK ("GROUP_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "CONFIG_INFO_AGGR" ADD CONSTRAINT "SYS_C0012378" CHECK ("DATUM_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "CONFIG_INFO_AGGR" ADD CONSTRAINT "SYS_C0012379" CHECK ("CONTENT" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Indexes structure for table CONFIG_INFO_AGGR
-- ----------------------------
CREATE UNIQUE INDEX "UK_DI_GR_T_D"
    ON "CONFIG_INFO_AGGR" ("DATA_ID" ASC, "GROUP_ID" ASC, "TENANT_ID" ASC, "DATUM_ID" ASC)
    LOGGING
PCTFREE 10
INITRANS 2
STORAGE (
  INITIAL 65536
  NEXT 1048576
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
  FLASH_CACHE DEFAULT
);

-- ----------------------------
-- Primary Key structure for table CONFIG_INFO_BETA
-- ----------------------------
ALTER TABLE "CONFIG_INFO_BETA" ADD CONSTRAINT "SYS_C0012433" PRIMARY KEY ("ID");

-- ----------------------------
-- Checks structure for table CONFIG_INFO_BETA
-- ----------------------------
ALTER TABLE "CONFIG_INFO_BETA" ADD CONSTRAINT "SYS_C0012363" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "CONFIG_INFO_BETA" ADD CONSTRAINT "SYS_C0012364" CHECK ("DATA_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "CONFIG_INFO_BETA" ADD CONSTRAINT "SYS_C0012365" CHECK ("GROUP_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "CONFIG_INFO_BETA" ADD CONSTRAINT "SYS_C0012366" CHECK ("CONTENT" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Indexes structure for table CONFIG_INFO_BETA
-- ----------------------------
CREATE UNIQUE INDEX "UK_D_G_T"
    ON "CONFIG_INFO_BETA" ("DATA_ID" ASC, "GROUP_ID" ASC, "TENANT_ID" ASC)
    LOGGING
PCTFREE 10
INITRANS 2
STORAGE (
  INITIAL 65536
  NEXT 1048576
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
  FLASH_CACHE DEFAULT
);

-- ----------------------------
-- Primary Key structure for table CONFIG_INFO_TAG
-- ----------------------------
ALTER TABLE "CONFIG_INFO_TAG" ADD CONSTRAINT "SYS_C0012435" PRIMARY KEY ("ID");

-- ----------------------------
-- Checks structure for table CONFIG_INFO_TAG
-- ----------------------------
ALTER TABLE "CONFIG_INFO_TAG" ADD CONSTRAINT "SYS_C0012381" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "CONFIG_INFO_TAG" ADD CONSTRAINT "SYS_C0012382" CHECK ("DATA_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "CONFIG_INFO_TAG" ADD CONSTRAINT "SYS_C0012383" CHECK ("GROUP_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "CONFIG_INFO_TAG" ADD CONSTRAINT "SYS_C0012385" CHECK ("CONTENT" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Indexes structure for table CONFIG_INFO_TAG
-- ----------------------------
CREATE UNIQUE INDEX "UK_D_G_T_T"
    ON "CONFIG_INFO_TAG" ("DATA_ID" ASC, "GROUP_ID" ASC, "TENANT_ID" ASC, "TAG_ID" ASC)
    LOGGING
PCTFREE 10
INITRANS 2
STORAGE (
  INITIAL 65536
  NEXT 1048576
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
  FLASH_CACHE DEFAULT
);

-- ----------------------------
-- Primary Key structure for table CONFIG_TAGS_RELATION
-- ----------------------------
ALTER TABLE "CONFIG_TAGS_RELATION" ADD CONSTRAINT "SYS_C0012436" PRIMARY KEY ("NID");

-- ----------------------------
-- Checks structure for table CONFIG_TAGS_RELATION
-- ----------------------------
ALTER TABLE "CONFIG_TAGS_RELATION" ADD CONSTRAINT "SYS_C0012388" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "CONFIG_TAGS_RELATION" ADD CONSTRAINT "SYS_C0012390" CHECK ("DATA_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "CONFIG_TAGS_RELATION" ADD CONSTRAINT "SYS_C0012391" CHECK ("GROUP_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "CONFIG_TAGS_RELATION" ADD CONSTRAINT "SYS_C007929" CHECK ("TAG_NAME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "CONFIG_TAGS_RELATION" ADD CONSTRAINT "SYS_C007932" CHECK ("NID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Indexes structure for table CONFIG_TAGS_RELATION
-- ----------------------------
CREATE INDEX "IDX_T"
    ON "CONFIG_TAGS_RELATION" ("TENANT_ID" ASC)
    LOGGING
PCTFREE 10
INITRANS 2
STORAGE (
  INITIAL 65536
  NEXT 1048576
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
  FLASH_CACHE DEFAULT
);

CREATE UNIQUE INDEX "UK_I_T_T"
    ON "CONFIG_TAGS_RELATION" ("ID" ASC, "TAG_NAME" ASC, "TAG_TYPE" ASC)
    LOGGING
PCTFREE 10
INITRANS 2
STORAGE (
  INITIAL 65536
  NEXT 1048576
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
  FLASH_CACHE DEFAULT
);

-- ----------------------------
-- Primary Key structure for table GROUP_CAPACITY
-- ----------------------------
ALTER TABLE "GROUP_CAPACITY" ADD CONSTRAINT "SYS_C0012438" PRIMARY KEY ("ID");

-- ----------------------------
-- Checks structure for table GROUP_CAPACITY
-- ----------------------------
ALTER TABLE "GROUP_CAPACITY" ADD CONSTRAINT "SYS_C0012393" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "GROUP_CAPACITY" ADD CONSTRAINT "SYS_C0012394" CHECK ("GROUP_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "GROUP_CAPACITY" ADD CONSTRAINT "SYS_C0012395" CHECK ("QUOTA" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "GROUP_CAPACITY" ADD CONSTRAINT "SYS_C0012396" CHECK ("USAGE" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "GROUP_CAPACITY" ADD CONSTRAINT "SYS_C0012397" CHECK ("MAX_SIZE" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "GROUP_CAPACITY" ADD CONSTRAINT "SYS_C0012398" CHECK ("MAX_AGGR_COUNT" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "GROUP_CAPACITY" ADD CONSTRAINT "SYS_C0012399" CHECK ("MAX_AGGR_SIZE" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "GROUP_CAPACITY" ADD CONSTRAINT "SYS_C0012400" CHECK ("MAX_HISTORY_COUNT" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Indexes structure for table GROUP_CAPACITY
-- ----------------------------
CREATE UNIQUE INDEX "UK_GR_ID"
    ON "GROUP_CAPACITY" ("GROUP_ID" ASC)
    LOGGING
PCTFREE 10
INITRANS 2
STORAGE (
  INITIAL 65536
  NEXT 1048576
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
  FLASH_CACHE DEFAULT
);

-- ----------------------------
-- Primary Key structure for table HIS_CONFIG_INFO
-- ----------------------------
ALTER TABLE "HIS_CONFIG_INFO" ADD CONSTRAINT "SYS_C0012439" PRIMARY KEY ("NID");

-- ----------------------------
-- Checks structure for table HIS_CONFIG_INFO
-- ----------------------------
ALTER TABLE "HIS_CONFIG_INFO" ADD CONSTRAINT "SYS_C0012408" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "HIS_CONFIG_INFO" ADD CONSTRAINT "SYS_C0012409" CHECK ("NID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "HIS_CONFIG_INFO" ADD CONSTRAINT "SYS_C0012410" CHECK ("DATA_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "HIS_CONFIG_INFO" ADD CONSTRAINT "SYS_C0012411" CHECK ("GROUP_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "HIS_CONFIG_INFO" ADD CONSTRAINT "SYS_C0012412" CHECK ("CONTENT" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Indexes structure for table HIS_CONFIG_INFO
-- ----------------------------
CREATE INDEX "IDX_DID"
    ON "HIS_CONFIG_INFO" ("DATA_ID" ASC)
    LOGGING
PCTFREE 10
INITRANS 2
STORAGE (
  INITIAL 65536
  NEXT 1048576
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
  FLASH_CACHE DEFAULT
);

CREATE INDEX "IDX_GMT_CREATE"
    ON "HIS_CONFIG_INFO" ("GMT_CREATE" ASC)
    LOGGING
PCTFREE 10
INITRANS 2
STORAGE (
  INITIAL 65536
  NEXT 1048576
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
  FLASH_CACHE DEFAULT
);

CREATE INDEX "IDX_GMT_MODIFIED"
    ON "HIS_CONFIG_INFO" ("GMT_MODIFIED" ASC)
    LOGGING
PCTFREE 10
INITRANS 2
STORAGE (
  INITIAL 65536
  NEXT 1048576
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
  FLASH_CACHE DEFAULT
);




-- ----------------------------
-- Indexes structure for table PERMISSIONS
-- ----------------------------
CREATE UNIQUE INDEX "UK_ROLE_PERMISSION"
    ON "PERMISSIONS" ("ROLE" ASC, "RESOURCE" ASC, "ACTION" ASC)
    LOGGING
PCTFREE 10
INITRANS 2
STORAGE (
  INITIAL 65536
  NEXT 1048576
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
  FLASH_CACHE DEFAULT
);

-- ----------------------------
-- Checks structure for table ROLES
-- ----------------------------
ALTER TABLE "ROLES" ADD CONSTRAINT "SYS_C0012406" CHECK ("USERNAME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "ROLES" ADD CONSTRAINT "SYS_C0012407" CHECK ("ROLE" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Indexes structure for table ROLES
-- ----------------------------
CREATE UNIQUE INDEX "IDX_USER_ROLE"
    ON "ROLES" ("USERNAME" ASC, "ROLE" ASC)
    LOGGING
PCTFREE 10
INITRANS 2
STORAGE (
  INITIAL 65536
  NEXT 1048576
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
  FLASH_CACHE DEFAULT
);

-- ----------------------------
-- Primary Key structure for table TENANT_CAPACITY
-- ----------------------------
ALTER TABLE "TENANT_CAPACITY" ADD CONSTRAINT "SYS_C0012440" PRIMARY KEY ("ID");

-- ----------------------------
-- Checks structure for table TENANT_CAPACITY
-- ----------------------------
ALTER TABLE "TENANT_CAPACITY" ADD CONSTRAINT "SYS_C0012416" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "TENANT_CAPACITY" ADD CONSTRAINT "SYS_C0012417" CHECK ("TENANT_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "TENANT_CAPACITY" ADD CONSTRAINT "SYS_C0012418" CHECK ("QUOTA" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "TENANT_CAPACITY" ADD CONSTRAINT "SYS_C0012419" CHECK ("USAGE" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "TENANT_CAPACITY" ADD CONSTRAINT "SYS_C0012420" CHECK ("MAX_SIZE" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "TENANT_CAPACITY" ADD CONSTRAINT "SYS_C0012421" CHECK ("MAX_AGGR_COUNT" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "TENANT_CAPACITY" ADD CONSTRAINT "SYS_C0012422" CHECK ("MAX_AGGR_SIZE" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "TENANT_CAPACITY" ADD CONSTRAINT "SYS_C0012423" CHECK ("MAX_HISTORY_COUNT" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Indexes structure for table TENANT_CAPACITY
-- ----------------------------
CREATE UNIQUE INDEX "UK_T"
    ON "TENANT_CAPACITY" ("TENANT_ID" ASC)
    LOGGING
PCTFREE 10
INITRANS 2
STORAGE (
  INITIAL 65536
  NEXT 1048576
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
  FLASH_CACHE DEFAULT
);

-- ----------------------------
-- Primary Key structure for table TENANT_INFO
-- ----------------------------
ALTER TABLE "TENANT_INFO" ADD CONSTRAINT "SYS_C0012441" PRIMARY KEY ("ID");

-- ----------------------------
-- Checks structure for table TENANT_INFO
-- ----------------------------
ALTER TABLE "TENANT_INFO" ADD CONSTRAINT "SYS_C0012426" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "TENANT_INFO" ADD CONSTRAINT "SYS_C0012427" CHECK ("KP" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Indexes structure for table TENANT_INFO
-- ----------------------------
CREATE INDEX "IDX_TENANT_ID"
    ON "TENANT_INFO" ("TENANT_ID" ASC)
    LOGGING
PCTFREE 10
INITRANS 2
STORAGE (
  INITIAL 65536
  NEXT 1048576
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
  FLASH_CACHE DEFAULT
);

CREATE UNIQUE INDEX "UK_TENANT_INFO_KPTENANTID"
    ON "TENANT_INFO" ("KP" ASC, "TENANT_ID" ASC)
    LOGGING
PCTFREE 10
INITRANS 2
STORAGE (
  INITIAL 65536
  NEXT 1048576
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
  FLASH_CACHE DEFAULT
);



-- ----------------------------
-- Primary Key structure for table USERS
-- ----------------------------
ALTER TABLE "USERS" ADD CONSTRAINT "SYS_C0012442" PRIMARY KEY ("USERNAME");

-- ----------------------------
-- Checks structure for table USERS
-- ----------------------------
ALTER TABLE "USERS" ADD CONSTRAINT "SYS_C0012430" CHECK ("USERNAME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "USERS" ADD CONSTRAINT "SYS_C0012431" CHECK ("PASSWORD" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "USERS" ADD CONSTRAINT "SYS_C0012432" CHECK ("ENABLED" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
